# Firm level data

In [1]:
import pandas as pd 
import numpy as np

In [2]:
# data=pd.read_csv("/Users/mengxi/Desktop/financial research/HAN/firm-county/ready_for_identified_affected_firm.csv")

path="/Users/effie/Desktop/term3/research_module/data/"
data=pd.read_csv(path+"firm_raw/ready_for_identified_affected_firm.csv")

In [3]:
data=data.reset_index().drop(['index'], axis=1)
data.index=data.index+1

data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,culilev,loanlev,credlev,nclilev,ltdblev,oncllev,wkcalev,shfdlev,random,random_sample_indicator
1,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2004.0,DE13216,60325,848006.0,...,22.850683,1.062639,2782852.0,13183967.0,0.0,13183967.0,13066443.0,46.305570,0.210340,0.569100
2,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2005.0,DE13216,60325,1425349.0,...,12.455903,0.000000,3930375.0,14087308.0,0.0,14087308.0,6997586.0,44.155380,0.975576,0.569100
3,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2007.0,DE13247,60329,432559.0,...,30.282000,0.000000,9386000.0,30841000.0,385000.0,30456000.0,13859000.0,29.427000,0.683262,0.569100
4,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2008.0,DE13247,60329,327591.0,...,38.544000,0.000000,9515000.0,30351000.0,43000.0,30308000.0,15419000.0,33.723000,0.797433,0.569100
5,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2009.0,DE13190,60311,605765.0,...,53.155000,0.000000,14610000.0,35291000.0,843000.0,34448000.0,21978000.0,66.289000,0.788825,0.569100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425095,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1.299578,0.000000,0.0,351464.0,328864.0,22600.0,1085100.0,0.047464,0.552223,0.642302
425096,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2013.0,DE13772,84307,1684.0,...,1.614374,0.000000,0.0,385389.0,341517.0,43872.0,877202.0,0.000000,0.583665,0.642302
425097,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2014.0,DE13772,84307,1740.0,...,2.527990,0.000000,0.0,371093.0,322595.0,48498.0,1832555.0,0.000000,0.791019,0.642302
425098,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,0.056661,0.000000,52982.0,7500.0,0.0,7500.0,1650209.0,2.513060,0.992052,0.897052
425099,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2013.0,DE13352,83022,4250.0,...,2.293341,0.000000,0.0,40154.0,1.0,40153.0,2032051.0,0.104991,0.802052,0.897052

In [4]:
data = data.query('bank_type_1=="Savings banks"|bank_type_2=="Savings banks"|bank_type_3=="Savings banks"')

# data = data.query('bank_type_1=="Savings banks"')
# data = data.query('bank_type_2=="Savings banks"')
# data = data.query('bank_type_3=="Savings banks"')

data = data.query('2003<year<2013')

data=data.reset_index().drop(['index'], axis=1)
data.index=data.index+1

In [5]:
# data['year'].value_counts()

In [6]:
query_data = data.query('empl<20')
data.loc[:,'small'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

query_data = data.query('year>2008')
data.loc[:,'year_post'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,credlev,nclilev,ltdblev,oncllev,wkcalev,shfdlev,random,random_sample_indicator,small,year_post
1,DE2010019552,90530,9053,9576,Roth,Bayern,2010.0,DE13190,60311,623634.0,...,1788868.0,1803490.0,1548368.0,255122.0,1539373.0,1.206676,0.824339,0.627641,1,1
2,DE2010019552,90530,9053,9576,Roth,Bayern,2011.0,DE13190,60311,527219.0,...,1271838.0,2661218.0,1997714.0,663504.0,2039143.0,1.542198,0.063830,0.627641,1,1
3,DE2010019552,90530,9053,9576,Roth,Bayern,2012.0,DE13190,60311,525789.0,...,1006868.0,1929164.0,1695760.0,233404.0,1851245.0,1.738739,0.538877,0.627641,1,1
4,DE2010019739,15827,1582,12072,Teltow-FlÃ¤ming,Brandenburg,2012.0,DE13124,10787,9839.0,...,NaN,1585586.0,1368936.0,216650.0,NaN,1.691839,0.630216,0.540324,1,1
5,DE2010035090,12305,1230,11000,"Berlin, Stadt",Berlin,2010.0,DE13885,30159,12353.0,...,NaN,207252.0,204452.0,2800.0,NaN,0.023150,0.853153,0.741225,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,85399,8539,9178,Freising,Bayern,2012.0,DE13338,85435,1835.0,...,0.0,67360.0,0.0,67360.0,0.0,0.183207,0.982878,0.733000,1,1
148110,DE8350273540,94362,9436,9278,Straubing-Bogen,Bayern,2012.0,DE13732,84028,3268.0,...,NaN,9000.0,0.0,9000.0,NaN,0.006883,0.832832,0.598721,1,1
148111,DE8350275036,84307,8430,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,137901.0,281000.0,281000.0,0.0,70215.0,0.000000,0.436713,0.500642,1,1
148112,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,0.0,351464.0,328864.0,22600.0,1085100.0,0.047464,0.552223,0.642302,1,1
148113,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,52982.0,7500.0,0.0,7500.0,1650209.0,2.513060,0.992052,0.897052,1,1

In [7]:
# data['country_bank_1']=[x[:2] for x in data['BvDID_bank_1']]
# data = data.query('country_bank_1=="DE"')

# data['country_bank_2']=[x[:2] for x in data['BvDID_bank_2']]
# data = data.query('country_bank_2=="DE"')

# data['country_bank_3']=[x[:2] for x in data['BvDID_bank_3']]
# data = data.query('country_bank_3=="DE"')

data['postcode_bank_1'] = data['postcode_bank_1'].fillna(0)
data['postcode_bank_2'] = data['postcode_bank_2'].fillna(0)
data['postcode_bank_3'] = data['postcode_bank_3'].fillna(0)


data['postcode_bank_1'] = data['postcode_bank_1'].astype(str)
data['postcode_bank_2'] = data['postcode_bank_2'].astype(int)
data['postcode_bank_3'] = data['postcode_bank_3'].astype(int)

data['postcode_bank_2'] = data['postcode_bank_2'].astype(str)
data['postcode_bank_3'] = data['postcode_bank_3'].astype(str)

data['postcode_bank_1']=np.where(data['postcode_bank_1'].str.len()<5, "0"+data['postcode_bank_1'], data['postcode_bank_1'])
data['postcode_bank_2']=np.where(data['postcode_bank_2'].str.len()<5, "0"+data['postcode_bank_2'], data['postcode_bank_2'])
data['postcode_bank_3']=np.where(data['postcode_bank_3'].str.len()<5, "0"+data['postcode_bank_3'], data['postcode_bank_3'])



data=data.reset_index().drop(['index'], axis=1)
data.index=data.index+1

In [8]:
query_data = data.query('bank_type_1=="Savings banks"')
data.loc[:,'bank_ty_1'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

query_data = data.query('bank_type_2=="Savings banks"')
data.loc[:,'bank_ty_2'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

query_data = data.query('bank_type_3=="Savings banks"')
data.loc[:,'bank_ty_3'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

In [9]:
data['post_affected_1_1']=[x[:1] for x in data['postcode_bank_1']]
data['post_affected_1_2']=[x[:1] for x in data['postcode_bank_2']]
data['post_affected_1_3']=[x[:1] for x in data['postcode_bank_3']]

data['post_affected_2_1']=[x[:2] for x in data['postcode_bank_1']]
data['post_affected_2_2']=[x[:2] for x in data['postcode_bank_2']]
data['post_affected_2_3']=[x[:2] for x in data['postcode_bank_3']]

# affected states: Sachsen, Nordrhein-Westfalen, Baden-WÃ¼rttemberg, Bayern, Hamburg, Schleswig-Holstein
# postcode of affected banks 
# 01 02 04 08 09
# 32 33 40 41 42 44 45 46 47 48151 48249 48282 48431 48599 48703 48653 49477 49525 50 51 52 53879 53937 53604 53111 57072 57462 57413 57439 57319 57392 57258 57271 58 59 
# 68 69 70 71 72 73 74 75 76646 76133 76530 76437 76275 77 78 79 88 89 97
# 63739 63897 8(80 81 82 83 84 85 86 87 88 89) 90 91 92 93 94 95 96 97 
# 20 21073 22 23701 23909 23552 24 25
# 34x 37x 43x


# bank_1
query_df_11 = data.query('postcode_bank_1=="48151"|postcode_bank_1=="48249"|postcode_bank_1=="48282"|postcode_bank_1=="48431"|postcode_bank_1=="48599"|postcode_bank_1=="48703"|postcode_bank_1=="48653"|postcode_bank_1=="49477"|postcode_bank_1=="49525"|postcode_bank_1=="53879"|postcode_bank_1=="53937"|postcode_bank_1=="53604"|postcode_bank_1=="53111"|postcode_bank_1=="57072"|postcode_bank_1=="57462"|postcode_bank_1=="57413"|postcode_bank_1=="57439"|postcode_bank_1=="57319"|postcode_bank_1=="57392"|postcode_bank_1=="57258"|postcode_bank_1=="57271"')          
data.loc[:,'bank_affected_11'] = data.index.map(lambda x : 1 if x in query_df_11.index else 0)

query_df_21 = data.query('post_affected_2_1=="01"|post_affected_2_1=="02"|post_affected_2_1=="04"|post_affected_2_1=="08"|post_affected_2_1=="09"|post_affected_2_1=="32"|post_affected_2_1=="33"|post_affected_2_1=="40"|post_affected_2_1=="41"|post_affected_2_1=="42"|post_affected_2_1=="44"|post_affected_2_1=="45"|post_affected_2_1=="46"|post_affected_2_1=="47"|post_affected_2_1=="50"|post_affected_2_1=="51"|post_affected_2_1=="52"|post_affected_2_1=="58"|post_affected_2_1=="59"|post_affected_2_1=="68"|post_affected_2_1=="69"|post_affected_2_1=="70"|post_affected_2_1=="71"|post_affected_2_1=="72"|post_affected_2_1=="73"|post_affected_2_1=="74"|post_affected_2_1=="75"|post_affected_2_1=="77"|post_affected_2_1=="78"|post_affected_2_1=="79"')                
data.loc[:,'bank_affected_21'] = data.index.map(lambda x : 1 if x in query_df_21.index else 0)

query_df_31 = data.query('post_affected_1_1=="8"|post_affected_2_1=="90"|post_affected_2_1=="91"|post_affected_2_1=="92"|post_affected_2_1=="93"|post_affected_2_1=="94"|post_affected_2_1=="95"|post_affected_2_1=="96"|post_affected_2_1=="97"|post_affected_2_1=="20"|post_affected_2_1=="22"|post_affected_2_1=="24"|post_affected_2_1=="25"|postcode_bank_1=="76646"|postcode_bank_1=="76133"|postcode_bank_1=="76530"|postcode_bank_1=="76437"|postcode_bank_1=="76275"|postcode_bank_1=="63739"|postcode_bank_1=="63897"|postcode_bank_1=="21073"|postcode_bank_1=="23701"|postcode_bank_1=="23909"|postcode_bank_1=="23552"')
data.loc[:,'bank_affected_31'] = data.index.map(lambda x : 1 if x in query_df_31.index else 0)

# bank_2
query_df_12 = data.query('postcode_bank_2=="48151"|postcode_bank_2=="48249"|postcode_bank_2=="48282"|postcode_bank_2=="48431"|postcode_bank_2=="48599"|postcode_bank_2=="48703"|postcode_bank_2=="48653"|postcode_bank_2=="49477"|postcode_bank_2=="49525"|postcode_bank_2=="53879"|postcode_bank_2=="53937"|postcode_bank_2=="53604"|postcode_bank_2=="53111"|postcode_bank_2=="57072"|postcode_bank_2=="57462"|postcode_bank_2=="57413"|postcode_bank_2=="57439"|postcode_bank_2=="57319"|postcode_bank_2=="57392"|postcode_bank_2=="57258"|postcode_bank_2=="57271"')          
data.loc[:,'bank_affected_12'] = data.index.map(lambda x : 1 if x in query_df_12.index else 0)

query_df_22 = data.query('post_affected_2_2=="01"|post_affected_2_2=="02"|post_affected_2_2=="04"|post_affected_2_2=="08"|post_affected_2_2=="09"|post_affected_2_2=="32"|post_affected_2_2=="33"|post_affected_2_2=="40"|post_affected_2_2=="41"|post_affected_2_2=="42"|post_affected_2_2=="44"|post_affected_2_2=="45"|post_affected_2_2=="46"|post_affected_2_2=="47"|post_affected_2_2=="50"|post_affected_2_2=="51"|post_affected_2_2=="52"|post_affected_2_2=="58"|post_affected_2_2=="59"|post_affected_2_2=="68"|post_affected_2_2=="69"|post_affected_2_2=="70"|post_affected_2_2=="71"|post_affected_2_2=="72"|post_affected_2_2=="73"|post_affected_2_2=="74"|post_affected_2_2=="75"|post_affected_2_2=="77"|post_affected_2_2=="78"|post_affected_2_2=="79"')                
data.loc[:,'bank_affected_22'] = data.index.map(lambda x : 1 if x in query_df_22.index else 0)

query_df_32 = data.query('post_affected_1_2=="8"|post_affected_2_2=="90"|post_affected_2_2=="91"|post_affected_2_2=="92"|post_affected_2_2=="93"|post_affected_2_2=="94"|post_affected_2_2=="95"|post_affected_2_2=="96"|post_affected_2_2=="97"|post_affected_2_2=="20"|post_affected_2_2=="22"|post_affected_2_2=="24"|post_affected_2_2=="25"|postcode_bank_2=="76646"|postcode_bank_2=="76133"|postcode_bank_2=="76530"|postcode_bank_2=="76437"|postcode_bank_2=="76275"|postcode_bank_2=="63739"|postcode_bank_2=="63897"|postcode_bank_2=="21073"|postcode_bank_2=="23701"|postcode_bank_2=="23909"|postcode_bank_2=="23552"')
data.loc[:,'bank_affected_32'] = data.index.map(lambda x : 1 if x in query_df_32.index else 0)

# bank_3
query_df_13 = data.query('postcode_bank_3=="48151"|postcode_bank_3=="48249"|postcode_bank_3=="48282"|postcode_bank_3=="48431"|postcode_bank_3=="48599"|postcode_bank_3=="48703"|postcode_bank_3=="48653"|postcode_bank_3=="49477"|postcode_bank_3=="49525"|postcode_bank_3=="53879"|postcode_bank_3=="53937"|postcode_bank_3=="53604"|postcode_bank_3=="53111"|postcode_bank_3=="57072"|postcode_bank_3=="57462"|postcode_bank_3=="57413"|postcode_bank_3=="57439"|postcode_bank_3=="57319"|postcode_bank_3=="57392"|postcode_bank_3=="57258"|postcode_bank_3=="57271"')          
data.loc[:,'bank_affected_13'] = data.index.map(lambda x : 1 if x in query_df_13.index else 0)

query_df_23 = data.query('post_affected_2_3=="01"|post_affected_2_3=="02"|post_affected_2_3=="04"|post_affected_2_3=="08"|post_affected_2_3=="09"|post_affected_2_3=="32"|post_affected_2_3=="33"|post_affected_2_3=="40"|post_affected_2_3=="41"|post_affected_2_3=="42"|post_affected_2_3=="44"|post_affected_2_3=="45"|post_affected_2_3=="46"|post_affected_2_3=="47"|post_affected_2_3=="50"|post_affected_2_3=="51"|post_affected_2_3=="52"|post_affected_2_3=="58"|post_affected_2_3=="59"|post_affected_2_3=="68"|post_affected_2_3=="69"|post_affected_2_3=="70"|post_affected_2_3=="71"|post_affected_2_3=="72"|post_affected_2_3=="73"|post_affected_2_3=="74"|post_affected_2_3=="75"|post_affected_2_3=="77"|post_affected_2_3=="78"|post_affected_2_3=="79"')                
data.loc[:,'bank_affected_23'] = data.index.map(lambda x : 1 if x in query_df_23.index else 0)

query_df_33 = data.query('post_affected_1_3=="8"|post_affected_2_3=="90"|post_affected_2_3=="91"|post_affected_2_3=="92"|post_affected_2_3=="93"|post_affected_2_3=="94"|post_affected_2_3=="95"|post_affected_2_3=="96"|post_affected_2_3=="97"|post_affected_2_3=="20"|post_affected_2_3=="22"|post_affected_2_3=="24"|post_affected_2_3=="25"|postcode_bank_3=="76646"|postcode_bank_3=="76133"|postcode_bank_3=="76530"|postcode_bank_3=="76437"|postcode_bank_3=="76275"|postcode_bank_3=="63739"|postcode_bank_3=="63897"|postcode_bank_3=="21073"|postcode_bank_3=="23701"|postcode_bank_3=="23909"|postcode_bank_3=="23552"')
data.loc[:,'bank_affected_33'] = data.index.map(lambda x : 1 if x in query_df_33.index else 0)


# 

query_df_1 = data.query('bank_affected_11==1|bank_affected_21==1|bank_affected_31==1')
data.loc[:,'bank_affected_1'] = data.index.map(lambda x : 1 if x in query_df_1.index else 0)

query_df_2 = data.query('bank_affected_12==1|bank_affected_22==1|bank_affected_32==1')
data.loc[:,'bank_affected_2'] = data.index.map(lambda x : 1 if x in query_df_2.index else 0)

query_df_3 = data.query('bank_affected_13==1|bank_affected_23==1|bank_affected_33==1')
data.loc[:,'bank_affected_3'] = data.index.map(lambda x : 1 if x in query_df_3.index else 0)

data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,bank_affected_31,bank_affected_12,bank_affected_22,bank_affected_32,bank_affected_13,bank_affected_23,bank_affected_33,bank_affected_1,bank_affected_2,bank_affected_3
1,DE2010019552,90530,9053,9576,Roth,Bayern,2010.0,DE13190,60311,623634.0,...,0,0,0,0,0,0,1,0,0,1
2,DE2010019552,90530,9053,9576,Roth,Bayern,2011.0,DE13190,60311,527219.0,...,0,0,0,0,0,0,1,0,0,1
3,DE2010019552,90530,9053,9576,Roth,Bayern,2012.0,DE13190,60311,525789.0,...,0,0,0,0,0,0,1,0,0,1
4,DE2010019739,15827,1582,12072,Teltow-FlÃ¤ming,Brandenburg,2012.0,DE13124,10787,9839.0,...,0,0,0,0,0,0,0,0,0,0
5,DE2010035090,12305,1230,11000,"Berlin, Stadt",Berlin,2010.0,DE13885,30159,12353.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,85399,8539,9178,Freising,Bayern,2012.0,DE13338,85435,1835.0,...,1,0,0,0,0,0,0,1,0,0
148110,DE8350273540,94362,9436,9278,Straubing-Bogen,Bayern,2012.0,DE13732,84028,3268.0,...,1,0,0,0,0,0,0,1,0,0
148111,DE8350275036,84307,8430,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,0,0,0,0,1,0,0
148112,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,1,0,0,1,1,1,1
148113,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,1,0,0,0,0,0,0,1,0,0

In [10]:
data['kreisschluessel'] = data['kreisschluessel'].astype(str)
data['kreisschluessel'] = np.where(data['kreisschluessel'].str.len()<5,"0"+data['kreisschluessel'],data['kreisschluessel'])

data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,bank_affected_31,bank_affected_12,bank_affected_22,bank_affected_32,bank_affected_13,bank_affected_23,bank_affected_33,bank_affected_1,bank_affected_2,bank_affected_3
1,DE2010019552,90530,9053,09576,Roth,Bayern,2010.0,DE13190,60311,623634.0,...,0,0,0,0,0,0,1,0,0,1
2,DE2010019552,90530,9053,09576,Roth,Bayern,2011.0,DE13190,60311,527219.0,...,0,0,0,0,0,0,1,0,0,1
3,DE2010019552,90530,9053,09576,Roth,Bayern,2012.0,DE13190,60311,525789.0,...,0,0,0,0,0,0,1,0,0,1
4,DE2010019739,15827,1582,12072,Teltow-FlÃ¤ming,Brandenburg,2012.0,DE13124,10787,9839.0,...,0,0,0,0,0,0,0,0,0,0
5,DE2010035090,12305,1230,11000,"Berlin, Stadt",Berlin,2010.0,DE13885,30159,12353.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,85399,8539,09178,Freising,Bayern,2012.0,DE13338,85435,1835.0,...,1,0,0,0,0,0,0,1,0,0
148110,DE8350273540,94362,9436,09278,Straubing-Bogen,Bayern,2012.0,DE13732,84028,3268.0,...,1,0,0,0,0,0,0,1,0,0
148111,DE8350275036,84307,8430,09277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,0,0,0,0,1,0,0
148112,DE8350276165,84339,8433,09277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,1,0,0,1,1,1,1
148113,DE8350277440,70469,7046,08111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,1,0,0,0,0,0,0,1,0,0

In [11]:
data.columns

Index(['BvDID_firm', 'plz_firm', 'matching', 'kreisschluessel', 'kreis',
       'bundesland', 'year', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       ...
       'bank_affected_31', 'bank_affected_12', 'bank_affected_22',
       'bank_affected_32', 'bank_affected_13', 'bank_affected_23',
       'bank_affected_33', 'bank_affected_1', 'bank_affected_2',
       'bank_affected_3'],
      dtype='object', length=110)

In [12]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'kreis', 'kreisschluessel', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected_1','bank_affected_2','bank_affected_3']]
data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected_1,bank_affected_2,bank_affected_3
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,0.824339,0.627641,1,1,0,0,1,0,0,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,0.063830,0.627641,1,1,0,0,1,0,0,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,0.538877,0.627641,1,1,0,0,1,0,0,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,0.630216,0.540324,1,1,0,1,0,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0.853153,0.741225,1,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.982878,0.733000,1,1,1,0,0,1,0,0
148110,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.832832,0.598721,1,1,1,0,0,1,0,0
148111,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.436713,0.500642,1,1,1,0,0,1,0,0
148112,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.552223,0.642302,1,1,1,0,0,1,1,1
148113,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,0.992052,0.897052,1,1,1,0,0,1,0,0

In [13]:
data.eval('tyaf_1 = bank_ty_1 * bank_affected_1', inplace=True)
data.eval('tyaf_2 = bank_ty_2 * bank_affected_2', inplace=True)
data.eval('tyaf_3 = bank_ty_3 * bank_affected_3', inplace=True)

data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected_1,bank_affected_2,bank_affected_3,tyaf_1,tyaf_2,tyaf_3
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1,0,0,1,0,0,1,0,0,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1,0,0,1,0,0,1,0,0,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1,0,0,1,0,0,1,0,0,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1,0,1,0,0,0,0,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,1,1,0,0,1,0,0,1,0,0
148110,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,1,1,0,0,1,0,0,1,0,0
148111,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,1,1,0,0,1,0,0,1,0,0
148112,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,1,1,0,0,1,1,1,1,0,0
148113,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,1,1,0,0,1,0,0,1,0,0

In [14]:
query_bank_affected = data.query('tyaf_1==1|tyaf_2==1|tyaf_3==1')
data.loc[:,'bank_affected'] = data.index.map(lambda x : 1 if x in query_bank_affected.index else 0)

data.eval('bank_affected_degree = tyaf_1 + tyaf_2 + tyaf_3', inplace=True)

/Users/effie/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/effie/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1745: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

In [15]:
data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,bank_ty_2,bank_ty_3,bank_affected_1,bank_affected_2,bank_affected_3,tyaf_1,tyaf_2,tyaf_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,0,1,0,0,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,0,1,0,0,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,0,1,0,0,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1,0,0,0,0,0,0,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0,0,1,0,0,1,0,0,1,1
148110,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0,0,1,0,0,1,0,0,1,1
148111,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0,0,1,0,0,1,0,0,1,1
148112,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0,0,1,1,1,1,0,0,1,1
148113,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,0,0,1,0,0,1,0,0,1,1

In [16]:
data['bank_affected'].value_counts()

1    97932
0    50181
Name: bank_affected, dtype: int64

In [17]:
data['bank_affected_degree'].value_counts()

1    94017
0    50181
2     3794
3      121
Name: bank_affected_degree, dtype: int64

In [18]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'kreis', 'kreisschluessel', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected', 'bank_affected_degree']]
data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1.206676,0.824339,0.627641,1,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1.542198,0.063830,0.627641,1,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1.738739,0.538877,0.627641,1,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1.691839,0.630216,0.540324,1,1,0,1,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0.023150,0.853153,0.741225,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.183207,0.982878,0.733000,1,1,1,0,0,1,1
148110,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.006883,0.832832,0.598721,1,1,1,0,0,1,1
148111,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.000000,0.436713,0.500642,1,1,1,0,0,1,1
148112,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.047464,0.552223,0.642302,1,1,1,0,0,1,1
148113,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,2.513060,0.992052,0.897052,1,1,1,0,0,1,1

In [19]:
#data.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211219 - data.csv')

In [20]:
data['ort_1'] = data['kreis'].str.replace("Bad Doberan", "Rostock, Landkreis", n=-1)
data['ort_2'] = data['ort_1'].str.replace("GÃ¼strow", "Rostock, Landkreis", n=-1)

data['ort_3'] = data['ort_2'].str.replace("Demmin", "Mecklenburgische Seenplatte", n=-1)
data['ort_4'] = data['ort_3'].str.replace("Neubrandenburg", "Mecklenburgische Seenplatte", n=-1)
data['ort_5'] = data['ort_4'].str.replace("MÃ¼ritz", "Mecklenburgische Seenplatte", n=-1)
data['ort_6'] = data['ort_5'].str.replace("Mecklenburg-Strelitz", "Mecklenburgische Seenplatte", n=-1)

data['ort_7'] = data['ort_6'].str.replace("Uecker-Randow", "Vorpommern-Greifswald", n=-1)
data['ort_8'] = data['ort_7'].str.replace("Ostvorpommern", "Vorpommern-Greifswald", n=-1)
data['ort_9'] = data['ort_8'].str.replace("Greifswald", "Vorpommern-Greifswald", n=-1)

data['ort_10'] = data['ort_9'].str.replace("Stralsund", "Vorpommern-RÃ¼gen", n=-1)
data['ort_11'] = data['ort_10'].str.replace("Nordvorpommern", "Vorpommern-RÃ¼gen", n=-1)
data['ort_12'] = data['ort_11'].str.replace("RÃ¼gen", "Vorpommern-RÃ¼gen", n=-1)

data['ort_13'] = data['ort_12'].str.replace("Wismar", "Nordwestmecklenburg", n=-1)

data['ort_14'] = data['ort_13'].str.replace("Parchim", "Ludwigslust-Parchim", n=-1)
data['ort_15'] = data['ort_14'].str.replace("Ludwigslust", "Ludwigslust-Parchim", n=-1)





data['ort_16'] = data['ort_15'].str.replace("Kamenz", "Bautzen", n=-1)
data['ort_17'] = data['ort_16'].str.replace("Hoyerswerda, Stadt", "Bautzen", n=-1)

data['ort_18'] = data['ort_17'].str.replace("Riesa-GroÃenhain", "MeiÃen", n=-1)

data['ort_19'] = data['ort_18'].str.replace("WeiÃeritzkreis", "SÃ¤chsische Schweiz-Osterzgebirge", n=-1)
data['ort_20'] = data['ort_19'].str.replace("SÃ¤chsische Schweiz", "SÃ¤chsische Schweiz-Osterzgebirge", n=-1)

data['ort_21'] = data['ort_20'].str.replace("DÃ¶beln", "Mittelsachsen", n=-1)
data['ort_22'] = data['ort_21'].str.replace("Mittweida", "Mittelsachsen", n=-1)
data['ort_23'] = data['ort_22'].str.replace("Freiberg", "Mittelsachsen", n=-1)

data['ort_24'] = data['ort_23'].str.replace("Delitzsch", "Nordsachsen", n=-1)
data['ort_25'] = data['ort_24'].str.replace("Torgau-Oschatz", "Nordsachsen", n=-1)

data['ort_26'] = data['ort_25'].str.replace("Leipziger Land", "Leipzig, Landkreis", n=-1)
data['ort_27'] = data['ort_26'].str.replace("Muldentalkreis", "Leipzig, Landkreis", n=-1)

data['ort_28'] = data['ort_27'].str.replace("Chemnitzer Land", "Zwickau", n=-1)
data['ort_29'] = data['ort_28'].str.replace("Zwickauer Land", "Zwickau", n=-1)
data['ort_30'] = data['ort_29'].str.replace("Zwickau, Stadt", "Zwickau", n=-1)

data['ort_31'] = data['ort_30'].str.replace("Mittlerer Erzgebirgskreis", "Erzgebirgskreis", n=-1)
data['ort_32'] = data['ort_31'].str.replace("Annaberg", "Erzgebirgskreis", n=-1)
data['ort_33'] = data['ort_32'].str.replace("Stollberg", "Erzgebirgskreis", n=-1)
data['ort_34'] = data['ort_33'].str.replace("Aue-Schwarzenberg", "Erzgebirgskreis", n=-1)

data['ort_35'] = data['ort_34'].str.replace("LÃ¶bau-Zittau", "GÃ¶rlitz", n=-1)
data['ort_36'] = data['ort_35'].str.replace("GÃ¶rlitz, Stadt", "GÃ¶rlitz", n=-1)
data['ort_37'] = data['ort_36'].str.replace("Niederschlesischer Oberlausitzkreis", "GÃ¶rlitz", n=-1)

data['ort_38'] = data['ort_37'].str.replace("Plauen, Stadt", "Vogtlandkreis", n=-1)



data['ort_39'] = data['ort_38'].str.replace("Bitterfeld", "Anhalt-Bitterfeld", n=-1)
data['ort_40'] = data['ort_39'].str.replace("KÃ¶then", "Anhalt-Bitterfeld", n=-1)

data['ort_41'] = data['ort_40'].str.replace("Dessau, Stadt", "Dessau-RoÃlau", n=-1)

data['ort_42'] = data['ort_41'].str.replace("BÃ¶rdekreis", "BÃ¶rde", n=-1)
data['ort_43'] = data['ort_42'].str.replace("Ohrekreis", "BÃ¶rde", n=-1)

data['ort_44'] = data['ort_43'].str.replace("Bernburg", "Salzlandkreis", n=-1)
data['ort_45'] = data['ort_44'].str.replace("SchÃ¶nebeck", "Salzlandkreis", n=-1)
data['ort_46'] = data['ort_45'].str.replace("Aschersleben-StaÃfurt", "Salzlandkreis", n=-1)

data['ort_47'] = data['ort_46'].str.replace("WeiÃenfels", "Burgenlandkreis", n=-1)

data['ort_48'] = data['ort_47'].str.replace("Merseburg-Querfurt", "Saalekreis", n=-1)
data['ort_49'] = data['ort_48'].str.replace("Saalkreis", "Saalekreis", n=-1)

data['ort_50'] = data['ort_49'].str.replace("Halberstadt", "Harz", n=-1)
data['ort_51'] = data['ort_50'].str.replace("Quedlinburg", "Harz", n=-1)
data['ort_52'] = data['ort_51'].str.replace("Wernigerode", "Harz", n=-1)

data['ort_53'] = data['ort_52'].str.replace("Anhalt-Zerbst", "Wittenberg", n=-1)

data['ort_54'] = data['ort_53'].str.replace("Halle (Saale), Stadt", "Halle (Saale)", n=-1)

data['ort_55'] = data['ort_54'].str.replace("Mansfelder Land", "Mansfeld-SÃ¼dharz", n=-1)
data['ort'] = data['ort_55'].str.replace("Sangerhausen", "Mansfeld-SÃ¼dharz", n=-1)

<ipython-input-20-ec6faf6ae130>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_1'] = data['kreis'].str.replace("Bad Doberan", "Rostock, Landkreis", n=-1)
<ipython-input-20-ec6faf6ae130>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_2'] = data['ort_1'].str.replace("GÃ¼strow", "Rostock, Landkreis", n=-1)
<ipython-input-20-ec6faf6ae130>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_3'] = data['ort_2'].str.replace("Demmin", "Mecklenburgische Seenplatte", n=-1)
<ipython-input-20-ec6faf6ae130>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_4'] = data['ort_3'].str.replace("Neubrandenburg", "Mecklenburgische Seenplatte", n=-1)
<ipython-input-20-ec6faf6ae130>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_5'] = data['ort_4'].str.replace("MÃ¼ritz", "Mecklenburgische Seenplatte", n=-1)

In [21]:
# data['regionalkey_1'] = data['kreisschluessel'].str.replace("Bad Doberan", "Rostock, Landkreis", n=-1)
# data['ort_2'] = data['ort_1'].str.replace("GÃ¼strow", "Rostock, Landkreis", n=-1)

# data['ort_3'] = data['ort_2'].str.replace("Demmin", "Mecklenburgische Seenplatte", n=-1)
# data['ort_4'] = data['ort_3'].str.replace("Neubrandenburg", "Mecklenburgische Seenplatte", n=-1)
# data['ort_5'] = data['ort_4'].str.replace("MÃ¼ritz", "Mecklenburgische Seenplatte", n=-1)
# data['ort_6'] = data['ort_5'].str.replace("Mecklenburg-Strelitz", "Mecklenburgische Seenplatte", n=-1)

# data['ort_7'] = data['ort_6'].str.replace("Uecker-Randow", "Vorpommern-Greifswald", n=-1)
# data['ort_8'] = data['ort_7'].str.replace("Ostvorpommern", "Vorpommern-Greifswald", n=-1)
# data['ort_9'] = data['ort_8'].str.replace("Greifswald", "Vorpommern-Greifswald", n=-1)

# data['ort_10'] = data['ort_9'].str.replace("Stralsund", "Vorpommern-RÃ¼gen", n=-1)
# data['ort_11'] = data['ort_10'].str.replace("Nordvorpommern", "Vorpommern-RÃ¼gen", n=-1)
# data['ort_12'] = data['ort_11'].str.replace("RÃ¼gen", "Vorpommern-RÃ¼gen", n=-1)

# data['ort_13'] = data['ort_12'].str.replace("Wismar", "Nordwestmecklenburg", n=-1)

# data['ort_14'] = data['ort_13'].str.replace("Parchim", "Ludwigslust-Parchim", n=-1)
# data['ort_15'] = data['ort_14'].str.replace("Ludwigslust", "Ludwigslust-Parchim", n=-1)


# regional key
data['regionalkey_1'] = data['kreisschluessel'].str.replace("13051", "13072", n=-1)
data['regionalkey_2'] = data['regionalkey_1'].str.replace("13053", "13072", n=-1)

data['regionalkey_3'] = data['regionalkey_2'].str.replace("13052", "13071", n=-1)
data['regionalkey_4'] = data['regionalkey_3'].str.replace("13002", "13071", n=-1)
data['regionalkey_5'] = data['regionalkey_4'].str.replace("13056", "13071", n=-1)
data['regionalkey_6'] = data['regionalkey_5'].str.replace("13055", "13071", n=-1)

data['regionalkey_7'] = data['regionalkey_6'].str.replace("13062", "13075", n=-1)
data['regionalkey_8'] = data['regionalkey_7'].str.replace("13059", "13075", n=-1)
data['regionalkey_9'] = data['regionalkey_8'].str.replace("13001", "13075", n=-1)

data['regionalkey_10'] = data['regionalkey_9'].str.replace("13005", "13073", n=-1)
data['regionalkey_11'] = data['regionalkey_10'].str.replace("13057", "13073", n=-1)
data['regionalkey_12'] = data['regionalkey_11'].str.replace("13061", "13073", n=-1)

data['regionalkey_13'] = data['regionalkey_12'].str.replace("13006", "13074", n=-1)
data['regionalkey_14'] = data['regionalkey_13'].str.replace("13058", "13074", n=-1)

data['regionalkey_15'] = data['regionalkey_14'].str.replace("13060", "13076", n=-1)
data['regionalkey_16'] = data['regionalkey_15'].str.replace("13054", "13076", n=-1)





data['regionalkey_17'] = data['regionalkey_16'].str.replace("14292", "14625", n=-1)
data['regionalkey_18'] = data['regionalkey_17'].str.replace("14262", "14625", n=-1)
data['regionalkey_19'] = data['regionalkey_18'].str.replace("14272", "14625", n=-1)

data['regionalkey_20'] = data['regionalkey_19'].str.replace("14285", "14627", n=-1)
data['regionalkey_21'] = data['regionalkey_20'].str.replace("14280", "14627", n=-1)

data['regionalkey_22'] = data['regionalkey_21'].str.replace("14290", "14628", n=-1)
data['regionalkey_23'] = data['regionalkey_22'].str.replace("14287", "14628", n=-1)

data['regionalkey_24'] = data['regionalkey_23'].str.replace("14375", "14522", n=-1)
data['regionalkey_25'] = data['regionalkey_24'].str.replace("14182", "14522", n=-1)
data['regionalkey_26'] = data['regionalkey_25'].str.replace("14177", "14522", n=-1)

data['regionalkey_27'] = data['regionalkey_26'].str.replace("14374", "14730", n=-1)
data['regionalkey_28'] = data['regionalkey_27'].str.replace("14389", "14730", n=-1)

data['regionalkey_29'] = data['regionalkey_28'].str.replace("14379", "14729", n=-1)
data['regionalkey_30'] = data['regionalkey_29'].str.replace("14383", "14729", n=-1)

data['regionalkey_31'] = data['regionalkey_30'].str.replace("14173", "14524", n=-1)
data['regionalkey_32'] = data['regionalkey_31'].str.replace("14193", "14524", n=-1)
data['regionalkey_33'] = data['regionalkey_32'].str.replace("14167", "14524", n=-1)

data['regionalkey_34'] = data['regionalkey_33'].str.replace("14181", "14521", n=-1)
data['regionalkey_35'] = data['regionalkey_34'].str.replace("14171", "14521", n=-1)
data['regionalkey_36'] = data['regionalkey_35'].str.replace("14188", "14521", n=-1)
data['regionalkey_37'] = data['regionalkey_36'].str.replace("14191", "14521", n=-1)

data['regionalkey_38'] = data['regionalkey_37'].str.replace("14286", "14626", n=-1)
data['regionalkey_39'] = data['regionalkey_38'].str.replace("14263", "14626", n=-1)
data['regionalkey_40'] = data['regionalkey_39'].str.replace("14284", "14626", n=-1)

data['regionalkey_41'] = data['regionalkey_40'].str.replace("14166", "14523", n=-1)
data['regionalkey_42'] = data['regionalkey_41'].str.replace("14178", "14523", n=-1)





data['regionalkey_43'] = data['regionalkey_42'].str.replace("15154", "15082", n=-1)
data['regionalkey_44'] = data['regionalkey_43'].str.replace("15159", "15082", n=-1)

data['regionalkey_45'] = data['regionalkey_44'].str.replace("15101", "15001", n=-1)

data['regionalkey_46'] = data['regionalkey_45'].str.replace("15355", "15083", n=-1)
data['regionalkey_47'] = data['regionalkey_46'].str.replace("15362", "15083", n=-1)

data['regionalkey_48'] = data['regionalkey_47'].str.replace("15153", "15089", n=-1)
data['regionalkey_49'] = data['regionalkey_48'].str.replace("15367", "15089", n=-1)
data['regionalkey_50'] = data['regionalkey_49'].str.replace("15352", "15089", n=-1)

data['regionalkey_51'] = data['regionalkey_50'].str.replace("15268", "15084", n=-1)
data['regionalkey_52'] = data['regionalkey_51'].str.replace("15256", "15084", n=-1)

data['regionalkey_53'] = data['regionalkey_52'].str.replace("15261", "15088", n=-1)
data['regionalkey_54'] = data['regionalkey_53'].str.replace("15265", "15088", n=-1)

data['regionalkey_55'] = data['regionalkey_54'].str.replace("15357", "15085", n=-1)
data['regionalkey_56'] = data['regionalkey_55'].str.replace("15364", "15085", n=-1)
data['regionalkey_57'] = data['regionalkey_56'].str.replace("15369", "15085", n=-1)

data['regionalkey_58'] = data['regionalkey_57'].str.replace("15151", "15091", n=-1)
data['regionalkey_59'] = data['regionalkey_58'].str.replace("15171", "15091", n=-1)

data['regionalkey_60'] = data['regionalkey_59'].str.replace("15202", "15002", n=-1)

data['regionalkey_61'] = data['regionalkey_60'].str.replace("15260", "15087", n=-1)
data['regionalkey_62'] = data['regionalkey_61'].str.replace("15266", "15087", n=-1)

data['regionalkey_63'] = data['regionalkey_62'].str.replace("15303", "15003", n=-1)
data['regionalkey_64'] = data['regionalkey_63'].str.replace("15358", "15086", n=-1)
data['regionalkey'] = data['regionalkey_64'].str.replace("15363", "15090", n=-1)

In [22]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'ort', 'regionalkey', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected', 'bank_affected_degree']]
data

,BvDID_firm,year,plz_firm,ort,regionalkey,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1.206676,0.824339,0.627641,1,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1.542198,0.063830,0.627641,1,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1.738739,0.538877,0.627641,1,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1.691839,0.630216,0.540324,1,1,0,1,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0.023150,0.853153,0.741225,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.183207,0.982878,0.733000,1,1,1,0,0,1,1
148110,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.006883,0.832832,0.598721,1,1,1,0,0,1,1
148111,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.000000,0.436713,0.500642,1,1,1,0,0,1,1
148112,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.047464,0.552223,0.642302,1,1,1,0,0,1,1
148113,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,2.513060,0.992052,0.897052,1,1,1,0,0,1,1

In [23]:
data['ort_a'] = data['ort'].str.replace("Aachen, Stadt", "Aachen", n=-1)
data['ort_b'] = data['ort_a'].str.replace("Aachen", "StÃ¤dteregion Aachen", n=-1)

data['ort_c'] = data['ort_b'].str.replace("Hamburg, Freie und Hansestadt", "Hamburg", n=-1)

data['ort_d'] = data['ort_c'].str.replace("Soltau-Fallingbostel", "Heidekreis", n=-1)

data['ort_e'] = data['ort_d'].str.replace("Oldenburg", "Oldenburg, Landkreis", n=-1)

data['ort_f'] = data['ort_e'].str.replace("Daun", "Vulkaneifel", n=-1)

data['ort_'] = data['ort_f'].str.replace(", Hansestadt", "", n=-1)

data.loc[(data.regionalkey == "09571") ,'ort_'] = 'Ansbach, Landkreis'
data.loc[(data.regionalkey == "13076") ,'ort_'] = 'Ludwigslust-Parchim'
data.loc[(data.regionalkey == "13073") ,'ort_'] = 'Vorpommern-RÃ¼gen'
data.loc[(data.regionalkey == "13075") ,'ort_'] = 'Vorpommern-Greifswald'
data.loc[(data.regionalkey == "14628") ,'ort_'] = 'SÃ¤chsische Schweiz-Osterzgebirge'

data.loc[(data.ort_ == "Chemnitz, Stadt") ,'regionalkey'] = '14511'
data.loc[(data.ort_ == "Dresden, Stadt") ,'regionalkey'] = '14612'
data.loc[(data.ort_ == "Leipzig, Stadt") ,'regionalkey'] = '14713'
data.loc[(data.ort_ == "Altmarkkreis Salzwedel") ,'regionalkey'] = '15081'
data.loc[(data.ort_ == "GÃ¶ttingen") ,'regionalkey'] = '03159'
data.loc[(data.ort_ == "Bautzen") ,'regionalkey'] = '14625'

<ipython-input-23-d8aca8d9cd80>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_a'] = data['ort'].str.replace("Aachen, Stadt", "Aachen", n=-1)
<ipython-input-23-d8aca8d9cd80>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_b'] = data['ort_a'].str.replace("Aachen", "StÃ¤dteregion Aachen", n=-1)
<ipython-input-23-d8aca8d9cd80>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_c'] = data['ort_b'].str.replace("Hamburg, Freie und Hansestadt", "Hamburg", n=-1)
<ipython-input-23-d8aca8d9cd80>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_d'] = data['ort_c'].str.replace("Soltau-Fallingbostel", "Heidekreis", n=-1)
<ipython-input-23-d8aca8d9cd80>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_e'] = data['ort_d'].str.replace("Oldenburg", "Oldenburg, Landkreis", n=-1)
<ipython-input-23-d8aca8d9cd80>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_f'] = data['ort_e'].str.replace("Daun", "Vulkaneifel", n=-1)
<ipython-input-23-d8aca8d9cd80>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ort_'] = data['ort_f'].str.replace(", Hansestadt", "", n=-1)
/Users/effie/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [24]:
data['regionalkey_a'] = data['regionalkey'].str.replace("05313", "05334", n=-1)
data['regionalkey_b'] = data['regionalkey_a'].str.replace("05354", "05334", n=-1)

data['regionalkey_c'] = data['regionalkey_b'].str.replace("2000", "2", n=-1)

data['regionalkey_'] = data['regionalkey_c'].str.replace("11000", "11", n=-1)



# æ²¡æå¬å¸ï¼
# 06413 Offenbach
# 07313 Landau in der Pfalz
# 07338 Rhein-Pfalz-Kreis
# 08125 Heilbronn, Landkreis
# 08215 Karlsruhe, Landkreis
# 09162 MÃ¼nchen
# 09363 Weiden i.d. OPf.

<ipython-input-24-1dd3a20b1340>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['regionalkey_a'] = data['regionalkey'].str.replace("05313", "05334", n=-1)
<ipython-input-24-1dd3a20b1340>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['regionalkey_b'] = data['regionalkey_a'].str.replace("05354", "05334", n=-1)
<ipython-input-24-1dd3a20b1340>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['regionalkey_c'] = data['regionalkey_b'].str.replace("2000", "2", n=-1)
<ipython-input-24-1dd3a20b1340>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['regionalkey_'] = data['regionalkey_c'].str.replace("11000", "11", n=-1)

In [25]:
# ort_df = data[['regionalkey_','ort_']]
# data['regionalkey_'].value_counts()
# data['ort_'].value_counts()

In [26]:
# ort_df = ort_df.drop_duplicates()
# ort_df=ort_df.reset_index().drop(['index'], axis=1)
# ort_df.index=ort_df.index+1
# ort_df

In [27]:
#ort_df.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211219_check county key.csv')

In [28]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'ort_', 'regionalkey_', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected', 'bank_affected_degree']]
data

,BvDID_firm,year,plz_firm,ort_,regionalkey_,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1.206676,0.824339,0.627641,1,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1.542198,0.063830,0.627641,1,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1.738739,0.538877,0.627641,1,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1.691839,0.630216,0.540324,1,1,0,1,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11,Berlin,DE13885,30159,12353.0,1332.0,...,0.023150,0.853153,0.741225,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148109,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.183207,0.982878,0.733000,1,1,1,0,0,1,1
148110,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.006883,0.832832,0.598721,1,1,1,0,0,1,1
148111,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.000000,0.436713,0.500642,1,1,1,0,0,1,1
148112,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.047464,0.552223,0.642302,1,1,1,0,0,1,1
148113,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,2.513060,0.992052,0.897052,1,1,1,0,0,1,1

In [29]:
# æædata
# data.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211219_firmdata.csv')

In [30]:
data0=data[data["year"]==2004]
id0=data0["BvDID_firm"].unique()
data1=data[data["year"]==2005]
id1=data1["BvDID_firm"].unique()
data2=data[data["year"]==2006]
id2=data2["BvDID_firm"].unique()
# data3=data[data["year"]==2007]
# id3=data3["BvDID_firm"].unique()
# data4=data[data["year"]==2008]
# id4=data4["BvDID_firm"].unique()

In [31]:
# id_all=set(list(id1)+list(id2)+list(id3)+list(id4))
# id_all=set(list(id1)+list(id2)+list(id3))
id_all=set(list(id0)+list(id1)+list(id2))

id_all

{'DE6110008825',
 'DE3190001005',
 'DE8270071196',
 'DE4130008669',
 'DE7330086955',
 'DE5190186010',
 'DE5010106309',
 'DE8190048529',
 'DE7330334620',
 'DE5210001689',
 'DE5330123213',
 'DE8010011037',
 'DE3310004745',
 'DE3310017151',
 'DE3170001103',
 'DE3190017359',
 'DE3490021353',
 'DE8270115093',
 'DE4110000129',
 'DE4010098995',
 'DE6110036308',
 'DE7050019261',
 'DE3030006990',
 'DE4090000659',
 'DE3410004298',
 'DE6110004400',
 'DE8170554176',
 'DE3190183086',
 'DE3170025764',
 'DE3030035244',
 'DE3190058259',
 'DE3190057711',
 'DE4090008911',
 'DE7050000584',
 'DE8350001433',
 'DE3070046990',
 'DE8070103264',
 'DE2230122592',
 'DE3130036869',
 'DE6070056043',
 'DE7110026806',
 'DE7290171974',
 'DE3070068951',
 'DE3490011644',
 'DE4250005778',
 'DE3130106386',
 'DE3410001446',
 'DE4010024485',
 'DE8110028678',
 'DE8010092092',
 'DE8330261482',
 'DE3070040686',
 'DE8110058206',
 'DE4090086114',
 'DE3250114118',
 'DE8250005257',
 'DE3310033353',
 'DE7290108199',
 'DE6150018267',
 'DE5050196475',
 'DE6150280177',
 'DE2290030652',
 'DE7290290042',
 'DE8110030017',
 'DE3070068922',
 'DE5190432366',
 'DE4250046481',
 'DE2310021796',
 'DE7110034856',
 'DE3190139507',
 'DE8070002175',
 'DE3310044794',
 'DE7290007406',
 'DE5270109905',
 'DE4050002053',
 'DE8270031481',
 'DE8230001771',
 'DE3290028968',
 'DE2110018881',
 'DE3310014325',
 'DE7370004849',
 'DE5050492512',
 'DE2310068271',
 'DE7010009383',
 'DE4330067744',
 'DE8110012309',
 'DE7330003690',
 'DE6150280713',
 'DE7330577534',
 'DE8050050095',
 'DE7330021478',
 'DE7290000346',
 'DE7290317173',
 'DE3070285856',
 'DE5250058146',
 'DE3430000892',
 'DE5210166657',
 'DE5150003254',
 'DE3290059477',
 'DE4250236161',
 'DE5330193673',
 'DE3210111365',
 'DE8110003215',
 'DE8250139273',
 'DE5050158825',
 'DE4010005930',
 'DE4070241770',
 'DE2030255754',
 'DE7170195759',
 'DE6190005574',
 'DE2330000672',
 'DE3150092668',
 'DE6110254093',
 'DE4250095086',
 'DE6070263656',
 'DE7370015574',
 'DE8030053138',
 'DE4050216444',
 'DE5030177932',
 'DE7330011375',
 'DE7330000425',
 'DE5330070411',
 'DE5030087836',
 'DE5170026568',
 'DE4250056417',
 'DE4110070279',
 'DE8010051705',
 'DE3070012622',
 'DE2370010537',
 'DE3190034210',
 'DE6070214415',
 'DE4010120330',
 'DE2310001680',
 'DE8210000251',
 'DE3070058884',
 'DE6210220469',
 'DE4250027264',
 'DE3190093764',
 'DE3490003882',
 'DE8170493865',
 'DE2090040519',
 'DE8090031411',
 'DE3070050798',
 'DE5330005098',
 'DE3030023411',
 'DE2350000559',
 'DE8330009917',
 'DE4050104236',
 'DE6070097911',
 'DE3270008993',
 'DE4070045674',
 'DE7290165143',
 'DE7330106975',
 'DE2290088053',
 'DE8030029601',
 'DE2190184555',
 'DE7010008080',
 'DE7050160209',
 'DE5170001052',
 'DE8250121902',
 'DE5290001074',
 'DE2010061796',
 'DE6150029762',
 'DE5030052035',
 'DE2130001177',
 'DE4110000440',
 'DE7110009696',
 'DE5310005879',
 'DE6170006675',
 'DE7290015824',
 'DE7310000087',
 'DE8210086217',
 'DE2230083301',
 'DE5290009604',
 'DE4210011007',
 'DE4330061763',
 'DE3070007590',
 'DE8230151831',
 'DE3170073385',
 'DE3190007355',
 'DE3310092912',
 'DE7050041976',
 'DE3090086705',
 'DE6110008305',
 'DE4230074133',
 'DE4190019539',
 'DE3190106614',
 'DE2190288662',
 'DE8190268664',
 'DE5330027907',
 'DE3210010692',
 'DE8190310661',
 'DE3490017256',
 'DE7290172217',
 'DE7070133027',
 'DE5330142876',
 'DE8350164094',
 'DE7290011629',
 'DE3070145414',
 'DE5370022713',
 'DE7130104198',
 'DE4110069025',
 'DE5210001477',
 'DE7330263980',
 'DE5190273193',
 'DE3490091333',
 'DE4250207208',
 'DE3070001221',
 'DE4110002781',
 'DE6210014659',
 'DE7050130460',
 'DE3490011685',
 'DE8350104075',
 'DE8270197284',
 'DE7130067744',
 'DE3330018137',
 'DE5170119375',
 'DE7370081053',
 'DE7370091010',
 'DE8030010526',
 'DE2390228453',
 'DE8190553586',
 'DE5290022617',
 'DE8270009767',
 'DE2270012255',
 'DE5030133567',
 'DE3070004314',
 'DE2190143761',
 'DE3190069692',
 'DE3250036048',
 'DE4170006583',
 'DE6150179530',
 'DE2150028161',
 'DE4110114933',
 'DE5030168663',
 'DE6290034687',
 'DE4070336762',
 'DE6150016819',
 'DE7290086388',
 'DE2250009129',
 'DE3070192819',
 'DE3190088174',
 'DE8190212641',
 'DE8010097334',
 'DE7330379382',
 'DE7110213035',
 'DE6150290264',
 'DE2150007593',
 'DE5030097220',
 'DE2030033153',
 'DE7010030438',
 'DE7110214962',
 'DE7010006032',
 'DE7290010599',
 'DE8190002143',
 'DE5230156794',
 'DE8250002824',
 'DE5330097114',
 'DE3290004942',
 'DE4250207880',
 'DE5330126547',
 'DE6150148165',
 'DE4250161268',
 'DE7290091634',
 'DE5330004015',
 'DE4250020298',
 'DE7330063578',
 'DE3190195086',
 'DE4250250868',
 'DE4250100983',
 'DE5030327959',
 'DE8150091309',
 'DE8190221575',
 'DE3490008548',
 'DE5190015735',
 'DE7330442796',
 'DE5070003452',
 'DE3190048285',
 'DE4150032724',
 'DE8330105941',
 'DE8150007677',
 'DE2150757709',
 'DE8190255199',
 'DE7170012747',
 'DE8270145525',
 'DE6070065715',
 'DE7290001372',
 'DE5030336224',
 'DE7230168328',
 'DE4010053995',
 'DE3070099902',
 'DE3090042263',
 'DE3190036260',
 'DE8350049731',
 'DE5010204308',
 'DE4050000651',
 'DE8290000325',
 'DE8130003988',
 'DE5110203098',
 'DE7030059480',
 'DE8250040858',
 'DE7070069812',
 'DE8330006066',
 'DE3150079909',
 'DE5030001957',
 'DE8170436949',
 'DE6110102126',
 'DE2070003148',
 'DE8070046163',
 'DE7290323291',
 'DE2370004596',
 'DE3070115293',
 'DE8110008793',
 'DE5010124811',
 'DE4210008605',
 'DE4090016266',
 'DE3370024122',
 'DE8250002240',
 'DE8270145506',
 'DE8350106575',
 'DE3250074167',
 'DE4270079758',
 'DE4250102139',
 'DE6150067670',
 'DE4070329955',
 'DE2190268764',
 'DE8270004757',
 'DE4310002589',
 'DE8190335211',
 'DE6110098576',
 'DE5330022103',
 'DE5210097900',
 'DE3310015780',
 'DE7370021222',
 'DE5330195643',
 'DE2310055172',
 'DE3130001564',
 'DE7330137905',
 'DE5010003249',
 'DE3070246517',
 'DE3310012486',
 'DE3230011929',
 'DE8190103162',
 'DE2230044687',
 'DE7050103759',
 'DE6210019875',
 'DE4110002777',
 'DE7330275298',
 'DE8070001690',
 'DE8270102337',
 'DE8170056436',
 'DE7070019112',
 'DE4310010781',
 'DE2250074526',
 'DE3070233920',
 'DE5330045897',
 'DE5010031765',
 'DE2190118408',
 'DE3170113082',
 'DE7330094792',
 'DE5190013848',
 'DE3170001199',
 'DE8270002029',
 'DE8330050540',
 'DE2190396212',
 'DE3150236215',
 'DE8190233419',
 'DE5070007903',
 'DE8270039268',
 'DE7050160488',
 'DE3190092117',
 'DE3070014086',
 'DE4250009092',
 'DE3270021547',
 'DE8350093660',
 'DE2190198850',
 'DE6150006156',
 'DE7290159134',
 'DE8190280538',
 'DE4110030936',
 'DE4070183464',
 'DE8070002486',
 'DE4250001322',
 'DE3230013784',
 'DE4190034813',
 'DE2250009008',
 'DE7330050281',
 'DE4250164577',
 'DE3190039702',
 'DE5030123321',
 'DE8010012816',
 'DE3190143211',
 'DE3330004440',
 'DE3310018093',
 'DE5190408744',
 'DE3070018545',
 'DE5030105543',
 'DE4190004047',
 'DE8350063620',
 'DE8310017147',
 'DE4250029731',
 'DE5190521935',
 'DE7110007368',
 'DE6150100737',
 'DE8030001461',
 'DE8150007011',
 'DE8070016748',
 'DE8170034392',
 'DE8190042266',
 'DE3130041408',
 'DE7290105744',
 'DE4030009868',
 'DE2050183842',
 'DE4250019675',
 'DE4070040710',
 'DE7330570298',
 'DE7110140335',
 'DE8250007530',
 'DE2290019178',
 'DE3170013129',
 'DE5310025356',
 'DE5250011667',
 'DE8310075670',
 'DE5330004098',
 'DE4290065824',
 'DE4050014142',
 'DE6290076868',
 'DE7370077672',
 'DE3150102942',
 'DE8310040003',
 'DE8270001603',
 'DE8190096558',
 'DE3150013697',
 'DE6110101966',
 'DE5030000054',
 'DE3290044134',
 'DE4050078846',
 'DE4070192666',
 'DE2250014738',
 'DE8190488188',
 'DE3070029883',
 'DE3130115782',
 'DE2030234327',
 'DE2290165657',
 'DE7250024216',
 'DE3050030549',
 'DE8010004026',
 'DE2190024513',
 'DE3490011823',
 'DE6190177892',
 'DE8230001860',
 'DE5230102055',
 'DE3170017174',
 'DE6290012976',
 'DE6150199012',
 'DE2030067276',
 'DE8150009252',
 'DE8350000416',
 'DE8290091756',
 'DE7070009558',
 'DE3310008458',
 'DE5330146124',
 'DE6290034925',
 'DE2011025844',
 'DE3070150020',
 'DE5190163430',
 'DE2210055536',
 'DE4230039908',
 'DE3150066299',
 'DE7270084797',
 'DE7330018543',
 'DE4130004029',
 'DE8250001655',
 'DE5190545089',
 'DE8190436524',
 'DE6210135055',
 'DE3130064762',
 'DE4010099459',
 'DE5030327716',
 'DE3070052587',
 'DE4110008972',
 'DE2190136763',
 'DE5330054739',
 'DE5170073919',
 'DE5010222476',
 'DE4010144873',
 'DE5030145696',
 'DE3190074148',
 'DE5270057102',
 'DE7330010642',
 'DE2290169789',
 'DE6090000146',
 'DE7110136614',
 'DE5130051913',
 'DE8250177246',
 'DE6110078656',
 'DE2190288140',
 'DE6150195665',
 'DE2190285290',
 'DE7290139953',
 'DE4250107068',
 'DE2310015369',
 'DE4250104162',
 'DE4070012463',
 'DE3070209942',
 'DE8330120747',
 'DE2370013704',
 'DE3190028195',
 'DE8270004764',
 'DE5030399637',
 'DE3070088175',
 'DE6150016929',
 'DE4130079433',
 'DE7290323267',
 'DE8270134269',
 'DE2050372206',
 'DE7330329282',
 'DE7110088839',
 'DE6210205268',
 'DE2210022975',
 'DE8150002248',
 'DE7330367366',
 'DE5310022274',
 'DE6070009855',
 'DE7290006805',
 'DE3070034218',
 'DE4250299899',
 'DE8270119678',
 'DE4250175044',
 'DE5030001288',
 'DE4110007585',
 'DE8110073076',
 'DE3070033156',
 'DE8170490822',
 'DE6150151173',
 'DE6210111850',
 'DE3310002308',
 'DE6110005148',
 'DE7290022425',
 'DE8270013434',
 'DE4050000598',
 'DE7330009249',
 'DE7290270526',
 'DE3070144560',
 'DE7370006040',
 'DE7290139609',
 'DE4110000231',
 'DE2090050656',
 'DE3070227934',
 'DE2410013304',
 'DE3190008761',
 'DE4250072293',
 'DE8250000426',
 'DE8270004728',
 'DE4210019313',
 'DE8170014104',
 'DE2310023846',
 'DE3130072867',
 'DE4110005025',
 'DE5010141979',
 'DE4250165701',
 'DE8170276633',
 'DE6130098083',
 'DE2310025079',
 'DE5010156624',
 'DE4290072174',
 'DE7110000618',
 'DE2010661073',
 'DE3490000925',
 'DE7370008937',
 'DE2290008594',
 'DE5310014040',
 'DE4290010109',
 'DE5030016381',
 'DE8170523596',
 'DE3430021957',
 'DE8230001894',
 'DE3170017791',
 'DE8310006048',
 'DE5230067221',
 'DE2310066970',
 'DE2410049752',
 'DE2210011680',
 'DE3370008678',
 'DE5330002736',
 'DE3410008426',
 'DE5230052459',
 'DE7070095517',
 'DE3070053207',
 'DE8170133720',
 'DE7370001709',
 'DE8350065939',
 'DE5110110898',
 'DE3070017306',
 'DE7330170037',
 'DE3190018494',
 'DE2090001717',
 'DE6270027709',
 'DE5230182596',
 'DE3290016389',
 'DE2070007508',
 'DE7050004011',
 'DE3190011741',
 'DE3250031561',
 'DE2050419198',
 'DE3430010240',
 'DE4050038882',
 'DE7010022677',
 'DE5190005789',
 'DE8150008097',
 'DE5030344092',
 'DE8010093790',
 'DE3070022132',
 'DE8190023753',
 'DE4010007733',
 'DE7330200006',
 'DE8270210683',
 'DE3070009836',
 'DE7130002747',
 'DE2310082928',
 'DE6110052069',
 'DE8210018926',
 'DE3190120916',
 'DE4030027756',
 'DE8270178686',
 'DE8150178410',
 'DE5030015742',
 'DE8150008004',
 'DE4070133466',
 'DE5250003228',
 'DE8010041704',
 'DE7330142195',
 'DE3290041981',
 'DE8070058968',
 'DE2010640945',
 'DE4010001998',
 'DE2310118128',
 'DE8190022018',
 'DE8230034438',
 'DE7290124757',
 'DE2110035848',
 'DE4290092575',
 'DE4110003820',
 'DE6290150042',
 'DE5070171559',
 'DE3050077070',
 'DE2190016467',
 'DE4050005794',
 'DE8330176530',
 'DE7330000044',
 'DE2190115059',
 'DE6270021350',
 'DE7190067835',
 'DE5050032770',
 'DE2390000743',
 'DE3070207675',
 'DE4110069787',
 'DE4190005108',
 'DE4270000927',
 'DE8270006305',
 'DE8170027016',
 'DE6210107260',
 'DE8270006417',
 'DE4270001632',
 'DE7010004889',
 'DE8330262140',
 'DE7350007182',
 'DE2010798125',
 'DE7070062143',
 'DE2010391850',
 'DE6110069147',
 'DE4250038394',
 'DE2130027144',
 'DE4130033904',
 'DE4010012773',
 'DE4050130674',
 'DE5330103244',
 'DE3070088757',
 'DE8330322533',
 'DE3070050103',
 'DE4010062361',
 'DE8190025935',
 'DE2310161674',
 'DE4070011527',
 'DE6110338013',
 'DE7290009155',
 'DE8270164946',
 'DE2150043909',
 'DE2050476374',
 'DE8290012658',
 'DE3490001747',
 'DE6110001136',
 'DE3050091853',
 'DE7370019964',
 'DE4010032616',
 'DE7310024092',
 'DE3070041735',
 'DE4250144147',
 'DE7210052166',
 'DE3330009322',
 'DE3170007759',
 'DE3070134091',
 'DE4310000577',
 'DE3150006670',
 'DE8150049969',
 'DE2150836879',
 'DE5070020949',
 'DE8190306835',
 'DE7330004031',
 'DE7370000560',
 'DE2330001253',
 'DE7350003331',
 'DE4110073214',
 'DE5030150310',
 'DE8230174002',
 'DE6170028686',
 'DE6130075758',
 'DE7010002221',
 'DE3090084926',
 'DE3070132531',
 'DE7110055721',
 'DE8190066020',
 'DE8010001626',
 'DE7330030234',
 'DE4010002384',
 'DE8190032960',
 'DE5330089679',
 'DE2290017967',
 'DE6090003764',
 'DE7290082659',
 'DE3250090773',
 'DE3070002862',
 'DE6110008864',
 'DE3330012444',
 'DE8150000517',
 'DE5250007131',
 'DE5190000497',
 'DE6090000614',
 'DE6150000418',
 'DE8190418830',
 'DE2230110801',
 'DE8270000029',
 'DE3490011883',
 'DE5030327955',
 'DE3070101531',
 'DE4090000135',
 'DE8250006357',
 'DE8270000846',
 'DE4250119921',
 'DE3090001123',
 'DE8170079020',
 'DE8190041163',
 'DE7010033894',
 'DE5230018207',
 'DE8050071814',
 'DE2290005139',
 'DE7330514123',
 'DE4050019258',
 'DE4150013464',
 'DE4290012785',
 'DE6150285147',
 'DE8290061765',
 'DE4150076694',
 'DE7130000050',
 'DE5110034175',
 'DE3070078793',
 'DE7050006250',
 'DE8110020827',
 'DE3070028931',
 'DE7370000495',
 'DE7370052357',
 'DE2011339613',
 'DE5330065329',
 'DE3070307266',
 'DE8190105316',
 'DE7110174297',
 'DE7350025046',
 'DE7010012524',
 'DE2370022926',
 'DE4110012576',
 'DE3130021155',
 'DE2290088055',
 'DE2190022974',
 'DE8150089904',
 'DE8190071615',
 'DE2210063887',
 'DE6110022182',
 'DE3270001931',
 'DE5110149492',
 'DE2210004959',
 'DE3070234243',
 'DE4250003569',
 'DE4150048543',
 'DE4250028500',
 'DE7130104563',
 'DE7130001072',
 'DE4190004190',
 'DE7290004771',
 'DE8350000201',
 'DE5030053082',
 'DE4290054909',
 'DE8150014319',
 'DE7110017314',
 'DE3070034601',
 'DE8270002826',
 'DE8030003509',
 'DE3450010833',
 'DE4110027704',
 'DE8350087943',
 'DE3070148778',
 'DE3430001827',
 'DE5190578594',
 'DE6150000703',
 'DE2290078074',
 'DE6270019619',
 'DE3170047536',
 'DE4250002672',
 'DE4070082461',
 'DE7330610010',
 'DE8250001151',
 'DE2190251877',
 'DE4070215772',
 'DE8090012460',
 'DE5210016064',
 'DE7190009165',
 'DE7370051382',
 'DE4010004442',
 'DE7330319514',
 'DE2190371991',
 'DE3170034894',
 'DE3310017898',
 'DE8030002730',
 'DE4050195177',
 'DE5330000240',
 'DE7330365341',
 'DE3070226162',
 'DE4350020470',
 'DE7290169779',
 'DE4050316118',
 'DE6070382987',
 'DE3070010495',
 'DE4310003527',
 'DE3290021210',
 'DE3290100290',
 'DE7190047247',
 'DE3310000053',
 'DE8190491020',
 'DE6070013737',
 'DE3310007862',
 'DE6210013102',
 'DE3290000451',
 'DE7070106519',
 'DE5170019154',
 'DE8150158608',
 'DE3150048735',
 'DE4250004172',
 'DE8330266518',
 'DE7290003572',
 'DE2310020021',
 'DE7330118919',
 'DE2030204022',
 'DE3070039120',
 'DE8110090398',
 'DE2050057944',
 'DE5030366328',
 'DE5350070268',
 'DE4090000833',
 'DE5190574340',
 'DE3070008067',
 'DE6270083646',
 'DE5330084939',
 'DE7330714916',
 'DE7050122692',
 'DE8310020676',
 'DE3310009837',
 'DE5310003605',
 'DE2310015352',
 'DE6150140564',
 'DE7010020592',
 'DE2310042565',
 'DE6130039481',
 'DE8190126108',
 'DE3310028141',
 'DE3330000623',
 'DE3490020498',
 'DE3250146947',
 'DE8290110480',
 'DE2190060167',
 'DE4050014140',
 'DE3190043356',
 'DE7130041754',
 'DE7330405175',
 'DE6150017732',
 'DE6150016565',
 'DE7010032002',
 'DE7070000349',
 'DE3070138103',
 'DE3110067317',
 'DE8310000698',
 'DE8190454139',
 'DE6210017153',
 'DE5010181439',
 'DE2290099078',
 'DE4110030320',
 'DE5010233564',
 'DE3310082089',
 'DE6150290254',
 'DE8270112057',
 'DE7070000824',
 'DE4170047318',
 'DE8270185359',
 'DE2070099248',
 'DE3150256765',
 'DE3310038524',
 'DE7150093065',
 'DE4250010274',
 'DE3150038724',
 'DE4190072527',
 'DE2290017344',
 'DE2150297678',
 'DE3070087147',
 'DE5030011173',
 'DE2310046801',
 'DE4250033273',
 'DE4250029291',
 'DE8230048181',
 'DE7270008387',
 'DE8010000488',
 'DE7270100181',
 'DE7010130230',
 'DE3330037694',
 'DE2330002708',
 'DE6210058813',
 'DE8110026559',
 'DE5030310142',
 'DE6150288213',
 'DE7330075763',
 'DE3250082639',
 'DE3290009144',
 'DE3070134655',
 'DE8350036869',
 'DE8350000880',
 'DE8330077166',
 'DE3310062897',
 'DE2210073310',
 'DE8170020360',
 'DE3070015204',
 'DE4110012987',
 'DE8190023993',
 'DE3130165891',
 'DE5070007901',
 'DE2250006341',
 'DE8190184271',
 'DE8230006904',
 'DE8190527047',
 'DE4290000399',
 'DE8270148540',
 'DE2290022280',
 'DE6150156606',
 'DE5010021996',
 'DE5190136330',
 'DE8070000571',
 'DE2190068392',
 'DE5330014435',
 'DE4250064858',
 'DE2050030582',
 'DE3090050832',
 'DE4210042263',
 'DE8330281438',
 'DE5210116558',
 'DE7330248812',
 'DE8010054740',
 'DE5350060275',
 'DE8270199791',
 'DE7150010946',
 'DE6090001744',
 'DE4250101113',
 'DE7330218945',
 'DE7290074864',
 'DE3130063112',
 'DE7330035721',
 'DE8110025288',
 'DE3210107317',
 'DE8350026088',
 'DE4250091789',
 'DE4330017717',
 'DE3370010470',
 'DE5070048946',
 'DE3190031449',
 'DE2310197783',
 'DE5350037488',
 'DE3190111594',
 'DE4290063825',
 'DE3110000851',
 'DE4290043606',
 'DE7150059127',
 'DE6110211849',
 'DE3070124433',
 'DE2310095440',
 'DE5010067651',
 ...}

In [32]:
data_useful=data[data['BvDID_firm'].isin(list(id_all))]
#data_useful.set_index(['BvDID_firm', 'year'], inplace=True)
data_useful=data_useful.reset_index().drop(['index'], axis=1)
data_useful.index=data_useful.index+1



data_useful

,BvDID_firm,year,plz_firm,ort_,regionalkey_,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010041272,2006.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,265857.0,79992.0,...,3.397223,0.061524,0.575035,1,0,0,0,1,1,1
2,DE2010041272,2007.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,302841.0,103003.0,...,2.990665,0.819242,0.575035,1,0,0,0,1,1,1
3,DE2010041272,2008.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,359251.0,126692.0,...,2.685565,0.925363,0.575035,1,0,0,0,1,1,1
4,DE2010041272,2009.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,605765.0,177120.0,...,2.495652,0.128524,0.575035,1,1,0,0,1,1,1
5,DE2010041272,2010.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,623634.0,370294.0,...,2.437330,0.728537,0.575035,1,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,DE8350106575,2011.0,84056,Landshut,09274,Bayern,DE13732,84028,3274.0,548.0,...,0.110567,0.033535,0.588138,1,1,1,0,0,1,1
7971,DE8350106575,2012.0,84056,Landshut,09274,Bayern,DE13732,84028,3268.0,564.0,...,0.117222,0.736541,0.588138,1,1,1,0,0,1,1
7972,DE8350164094,2006.0,85356,Freising,09178,Bayern,DE42769,85354,1159.0,102.0,...,0.000000,0.536886,0.660865,1,0,1,0,0,1,1
7973,DE8350164094,2007.0,85356,Freising,09178,Bayern,DE42769,85354,1190.0,144.0,...,0.077424,0.861183,0.660865,1,0,1,0,0,1,1
7974,DE8350164094,2012.0,85356,Freising,09178,Bayern,DE42769,85354,1258.0,102.0,...,0.593000,0.199183,0.660865,1,1,1,0,0,1,1

In [33]:
data_useful["cf_ratio"]=data_useful["cf"]/(data_useful["toaslev"]*10**6)
data_useful["gros_ratio"]=data_useful["groslev"]/(data_useful["toaslev"]*10**6)
data_useful["shfd_ratio"]=data_useful["shfdlev"]/data_useful["toaslev"]
data_useful["staf_ave"]=data_useful["staflev"]/data_useful["empllev"]
data_useful["staf_ln"]=np.log(data_useful["staf_ave"])

# recalculate toas in ln
data_useful["toas_lev"]=data_useful["toaslev"]+1
data_useful["toas_ln"]=np.log(data_useful["toas_lev"])

# sales in million
data_useful["turn_lev"]=(data_useful["turnlev"]/10**6)+1
data_useful["turn_ln"]=np.log(data_useful["turn_lev"])

In [34]:
data_useful

,BvDID_firm,year,plz_firm,ort_,regionalkey_,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,bank_affected_degree,cf_ratio,gros_ratio,shfd_ratio,staf_ave,staf_ln,toas_lev,toas_ln,turn_lev,turn_ln
1,DE2010041272,2006.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,265857.0,79992.0,...,1,0.075024,NaN,0.042334,48871.675978,10.796953,81.248314,4.397510,128.884630,4.858918
2,DE2010041272,2007.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,302841.0,103003.0,...,1,0.091505,NaN,0.038756,49828.607527,10.816345,78.166190,4.358837,150.773620,5.015780
3,DE2010041272,2008.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,359251.0,126692.0,...,1,0.070409,NaN,0.031984,52628.015345,10.871004,84.965980,4.442251,199.344200,5.295033
4,DE2010041272,2009.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,605765.0,177120.0,...,1,0.061911,NaN,0.029387,44985.775956,10.714102,85.924355,4.453467,119.532216,4.783586
5,DE2010041272,2010.0,13407,"Berlin, Stadt",11,Berlin,DE13190,60311,623634.0,370294.0,...,1,0.042470,NaN,0.027559,51404.482353,10.847481,89.440920,4.493578,146.464800,4.986785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,DE8350106575,2011.0,84056,Landshut,09274,Bayern,DE13732,84028,3274.0,548.0,...,1,0.161112,NaN,0.202240,33063.769231,10.406193,1.546713,0.436132,2.317667,0.840561
7971,DE8350106575,2012.0,84056,Landshut,09274,Bayern,DE13732,84028,3268.0,564.0,...,1,0.057209,NaN,0.216084,36853.846154,10.514715,1.542484,0.433394,2.320461,0.841766
7972,DE8350164094,2006.0,85356,Freising,09178,Bayern,DE42769,85354,1159.0,102.0,...,1,0.230300,NaN,0.000000,17312.543860,9.759187,2.136564,0.759199,5.152020,1.639389
7973,DE8350164094,2007.0,85356,Freising,09178,Bayern,DE42769,85354,1190.0,144.0,...,1,0.207050,NaN,0.076367,19426.391304,9.874388,2.013842,0.700044,6.110219,1.809963
7974,DE8350164094,2012.0,85356,Freising,09178,Bayern,DE42769,85354,1258.0,102.0,...,1,NaN,NaN,0.364251,NaN,NaN,2.628000,0.966223,NaN,NaN

In [35]:
data_check = data_useful[['BvDID_firm','year','bank_affected','empl','empllev','staf_ave','toas_ln','toas','toaslev','toas_lev','turn','turnlev','turn_lev','turn_ln','shfd_ratio','gros_ratio','cf_ratio','bank_affected_degree']]
data_check

,BvDID_firm,year,bank_affected,empl,empllev,staf_ave,toas_ln,toas,toaslev,toas_lev,turn,turnlev,turn_lev,turn_ln,shfd_ratio,gros_ratio,cf_ratio,bank_affected_degree
1,DE2010041272,2006.0,1,5.883322,358.0,48871.675978,4.397510,18.200636,80.248314,81.248314,18.666639,127884630.0,128.884630,4.858918,0.042334,NaN,0.075024,1
2,DE2010041272,2007.0,1,5.921578,372.0,49828.607527,4.358837,18.161472,77.166190,78.166190,18.824635,149773620.0,150.773620,5.015780,0.038756,NaN,0.091505,1
3,DE2010041272,2008.0,1,5.971262,391.0,52628.015345,4.442251,18.245922,83.965980,84.965980,19.105514,198344200.0,199.344200,5.295033,0.031984,NaN,0.070409,1
4,DE2010041272,2009.0,1,5.905362,366.0,44985.775956,4.453467,18.257271,84.924355,85.924355,18.590695,118532216.0,119.532216,4.783586,0.029387,NaN,0.061911,1
5,DE2010041272,2010.0,1,5.831882,340.0,51404.482353,4.493578,18.297845,88.440920,89.440920,18.795445,145464800.0,146.464800,4.986785,0.027559,NaN,0.042470,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7970,DE8350106575,2011.0,1,2.639057,13.0,33063.769231,0.436132,13.211681,0.546713,1.546713,14.091374,1317667.0,2.317667,0.840561,0.202240,NaN,0.161112,1
7971,DE8350106575,2012.0,1,2.639057,13.0,36853.846154,0.433394,13.203916,0.542484,1.542484,14.093492,1320461.0,2.320461,0.841766,0.216084,NaN,0.057209,1
7972,DE8350164094,2006.0,1,4.060443,57.0,17312.543860,0.759199,13.943521,1.136564,2.136564,15.239106,4152020.0,5.152020,1.639389,0.000000,NaN,0.230300,1
7973,DE8350164094,2007.0,1,4.248495,69.0,19426.391304,0.700044,13.829259,1.013842,2.013842,15.446753,5110219.0,6.110219,1.809963,0.076367,NaN,0.207050,1
7974,DE8350164094,2012.0,1,4.127134,61.0,NaN,0.966223,14.302863,1.628000,2.628000,NaN,NaN,NaN,NaN,0.364251,NaN,NaN,1

In [36]:
data_check_1 = data_check[['BvDID_firm','bank_affected','empllev','staf_ave','toas_lev','turn_lev','shfd_ratio','gros_ratio','cf_ratio','bank_affected_degree']]
data_check_1.describe()
# paperä¸­ï¼turn_levå¹³åä¸º6.24ï¼toas_levå¹³åä¸º6.04ï¼empllevå¹³åä¸º70

,bank_affected,empllev,staf_ave,toas_lev,turn_lev,shfd_ratio,gros_ratio,cf_ratio,bank_affected_degree
count,7974.000000,7974.000000,7.195000e+03,7974.000000,5823.000000,7974.000000,82.000000,7033.000000,7974.000000
mean,0.701781,235.136067,4.996740e+04,66.415423,73.637571,0.388376,0.588535,0.080575,0.735265
std,0.457505,601.978368,1.069220e+05,271.393878,232.317716,0.234633,0.389193,0.163240,0.515427
min,0.000000,1.000000,3.880000e+01,1.029278,1.000697,0.000000,0.082216,-3.273844,0.000000
25%,0.000000,37.000000,3.638608e+04,6.970852,10.008145,0.207489,0.291338,0.038088,0.000000
50%,1.000000,84.000000,4.639338e+04,16.158465,23.328052,0.370623,0.456251,0.072925,1.000000
75%,1.000000,198.000000,5.644151e+04,47.842548,56.428260,0.554272,1.004280,0.126171,1.000000
max,1.000000,11450.000000,7.873698e+06,6810.000000,5956.000000,0.994138,1.248863,3.100047,3.000000

In [37]:
data_useful.to_csv(path_or_buf=path+"firm_clean/ready_for_regression.csv")

# data_useful.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211221_ready_for_regression.csv')

In [38]:
data_useful['bank_affected'].value_counts()

1    5596
0    2378
Name: bank_affected, dtype: int64

In [39]:
data_useful['bank_affected_degree'].value_counts()

1    5345
0    2378
2     235
3      16
Name: bank_affected_degree, dtype: int64

In [40]:
ddddddd

NameError: name 'ddddddd' is not defined

# County level data

In [41]:
group = data_useful.groupby('BvDID_firm')
affected_index = data_useful.groupby('BvDID_firm').mean()['bank_affected']
df = affected_index.to_frame('affected_index')

query_df = df.query('affected_index!=0')
df.loc[:,'affected_firm'] = df.index.map(lambda x : 1 if x in query_df.index else 0)
df

              affected_index  affected_firm
BvDID_firm
DE2010041272             1.0              1
DE2010061796             1.0              1
DE2010391850             0.0              0
DE2010473501             0.0              0
DE2010640945             0.0              0
...                      ...            ...
DE8350087943             1.0              1
DE8350093660             1.0              1
DE8350104075             1.0              1
DE8350106575             1.0              1
DE8350164094             1.0              1

[1267 rows x 2 columns]

In [42]:
df['affected_index'].value_counts()

1.000000    877
0.000000    385
0.428571      1
0.857143      1
0.142857      1
0.500000      1
0.875000      1
Name: affected_index, dtype: int64

In [43]:
df_1 = df.query('affected_index==0.5|affected_index==0.8|affected_index==0.75')

df_1

              affected_index  affected_firm
BvDID_firm
DE5290001074             0.5              1

In [44]:
data_1 = data.query('BvDID_firm=="DE2310133781"|BvDID_firm=="DE3290004653"')

data_1

,BvDID_firm,year,plz_firm,ort_,regionalkey_,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
20163,DE2310133781,2007.0,49143,OsnabrÃ¼ck,03459,Niedersachsen,DE13381,95444,2072.0,349.0,...,0.038126,0.797938,0.706849,1,0,1,1,1,1,1
20164,DE2310133781,2008.0,49143,OsnabrÃ¼ck,03459,Niedersachsen,DE13381,95444,2018.0,398.0,...,0.037362,0.877182,0.706849,1,0,1,1,1,1,1
20165,DE2310133781,2009.0,49143,OsnabrÃ¼ck,03459,Niedersachsen,DE13381,95444,2048.0,194.0,...,0.228036,0.280201,0.706849,1,1,1,1,1,1,1
20166,DE2310133781,2010.0,49143,OsnabrÃ¼ck,03459,Niedersachsen,DE13450,49324,1139.0,104.0,...,0.334857,0.524534,0.706849,1,1,1,1,0,0,0
20167,DE2310133781,2011.0,49143,OsnabrÃ¼ck,03459,Niedersachsen,DE13216,60325,1867699.0,1552399.0,...,0.537464,0.990543,0.706849,1,1,0,1,1,0,0
20168,DE2310133781,2012.0,49143,OsnabrÃ¼ck,03459,Niedersachsen,DE13450,49324,1148.0,65.0,...,0.539362,0.463149,0.706849,1,1,1,1,0,0,0
38919,DE3290004653,2008.0,6886,Wittenberg,15091,Sachsen-Anhalt,DE13696,59590,210.0,14.0,...,1.393655,0.773889,0.757194,1,0,1,1,1,1,1
38920,DE3290004653,2009.0,6886,Wittenberg,15091,Sachsen-Anhalt,DE13696,59590,232.0,23.0,...,1.623327,0.861549,0.757194,1,1,1,1,1,1,1
38921,DE3290004653,2010.0,6886,Wittenberg,15091,Sachsen-Anhalt,DE13696,59590,241.0,20.0,...,1.865229,0.915228,0.757194,1,1,1,1,1,1,1
38922,DE3290004653,2011.0,6886,Wittenberg,15091,Sachsen-Anhalt,DE13696,59590,254.0,26.0,...,2.243508,0.757642,0.757194,1,1,1,1,1,1,1
38923,DE3290004653,2012.0,6886,Wittenberg,15091,Sachsen-Anhalt,DE43071,06886,1277.0,240.0,...,2.406114,0.704148,0.757194,1,1,1,1,1,0,0

In [45]:
group_1 = data_useful.groupby('regionalkey_')
firms_no = data_useful.groupby('regionalkey_').count()['BvDID_firm']
county_data_1 = firms_no.to_frame('firms_no')

data_2=data_useful[data_useful['bank_affected']==1]
data_2

firms_aff_no = data_2.groupby('regionalkey_').count()['bank_affected']
county_data_2 = firms_aff_no.to_frame('firms_aff_no')

county_data = pd.merge(left=county_data_1, right=county_data_2, on='regionalkey_', how='left')

county_data['ratio']=county_data["firms_aff_no"]/county_data["firms_no"]

In [46]:
county_data

              firms_no  firms_aff_no  ratio
regionalkey_
01001                2           2.0    1.0
01002               20          20.0    1.0
01003               15          15.0    1.0
01004               26          26.0    1.0
01053               14          14.0    1.0
...                ...           ...    ...
16072                4           4.0    1.0
16073               26           NaN    NaN
16074                7           NaN    NaN
16076                7           NaN    NaN
16077                8           8.0    1.0

[301 rows x 3 columns]

In [47]:
county_data.to_csv(path_or_buf=path+"firm_clean/key for county identification.csv")