# Firm level data

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data=pd.read_csv("/Users/mengxi/Desktop/financial research/HAN/firm-county/ready_for_identified_affected_firm.csv")

# data=pd.read_stata("/Users/mengxi/Desktop/financial research/final/211216_firm_sample_21.dta")

In [3]:
data=data.reset_index().drop(['index'], axis=1)
data.index=data.index+1

data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,culilev,loanlev,credlev,nclilev,ltdblev,oncllev,wkcalev,shfdlev,random,random_sample_indicator
1,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2004.0,DE13216,60325,848006.0,...,22.850683,1.062639,2782852.0,13183967.0,0.0,13183967.0,13066443.0,46.305570,0.210340,0.569100
2,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2005.0,DE13216,60325,1425349.0,...,12.455903,0.000000,3930375.0,14087308.0,0.0,14087308.0,6997586.0,44.155380,0.975576,0.569100
3,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2007.0,DE13247,60329,432559.0,...,30.282000,0.000000,9386000.0,30841000.0,385000.0,30456000.0,13859000.0,29.427000,0.683262,0.569100
4,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2008.0,DE13247,60329,327591.0,...,38.544000,0.000000,9515000.0,30351000.0,43000.0,30308000.0,15419000.0,33.723000,0.797433,0.569100
5,DE2010000074,10178,1017,11000,"Berlin, Stadt",Berlin,2009.0,DE13190,60311,605765.0,...,53.155000,0.000000,14610000.0,35291000.0,843000.0,34448000.0,21978000.0,66.289000,0.788825,0.569100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
425095,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1.299578,0.000000,0.0,351464.0,328864.0,22600.0,1085100.0,0.047464,0.552223,0.642302
425096,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2013.0,DE13772,84307,1684.0,...,1.614374,0.000000,0.0,385389.0,341517.0,43872.0,877202.0,0.000000,0.583665,0.642302
425097,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2014.0,DE13772,84307,1740.0,...,2.527990,0.000000,0.0,371093.0,322595.0,48498.0,1832555.0,0.000000,0.791018,0.642302
425098,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,0.056661,0.000000,52982.0,7500.0,0.0,7500.0,1650209.0,2.513060,0.992052,0.897052
425099,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2013.0,DE13352,83022,4250.0,...,2.293341,0.000000,0.0,40154.0,1.0,40153.0,2032051.0,0.104991,0.802052,0.897052

In [4]:
data = data.query('bank_type_1=="Savings banks"|bank_type_2=="Savings banks"|bank_type_3=="Savings banks"')

# data = data.query('bank_type_1=="Savings banks"')
# data = data.query('bank_type_2=="Savings banks"')
# data = data.query('bank_type_3=="Savings banks"')

data = data.query('2004<year<2013')

data=data.reset_index().drop(['index'], axis=1)
data.index=data.index+1

In [5]:
# data['year'].value_counts()

In [6]:
query_data = data.query('empl<20')
data.loc[:,'small'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

query_data = data.query('year>2008')
data.loc[:,'year_post'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,credlev,nclilev,ltdblev,oncllev,wkcalev,shfdlev,random,random_sample_indicator,small,year_post
1,DE2010019552,90530,9053,9576,Roth,Bayern,2010.0,DE13190,60311,623634.0,...,1788868.0,1803490.0,1548368.0,255122.0,1539373.0,1.206676,0.824339,0.627641,1,1
2,DE2010019552,90530,9053,9576,Roth,Bayern,2011.0,DE13190,60311,527219.0,...,1271838.0,2661218.0,1997714.0,663504.0,2039143.0,1.542198,0.063830,0.627641,1,1
3,DE2010019552,90530,9053,9576,Roth,Bayern,2012.0,DE13190,60311,525789.0,...,1006868.0,1929164.0,1695760.0,233404.0,1851245.0,1.738739,0.538877,0.627641,1,1
4,DE2010019739,15827,1582,12072,Teltow-FlÃ¤ming,Brandenburg,2012.0,DE13124,10787,9839.0,...,NaN,1585586.0,1368936.0,216650.0,NaN,1.691839,0.630216,0.540324,1,1
5,DE2010035090,12305,1230,11000,"Berlin, Stadt",Berlin,2010.0,DE13885,30159,12353.0,...,NaN,207252.0,204452.0,2800.0,NaN,0.023150,0.853153,0.741225,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,85399,8539,9178,Freising,Bayern,2012.0,DE13338,85435,1835.0,...,0.0,67360.0,0.0,67360.0,0.0,0.183207,0.982878,0.733000,1,1
148103,DE8350273540,94362,9436,9278,Straubing-Bogen,Bayern,2012.0,DE13732,84028,3268.0,...,NaN,9000.0,0.0,9000.0,NaN,0.006883,0.832832,0.598721,1,1
148104,DE8350275036,84307,8430,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,137901.0,281000.0,281000.0,0.0,70215.0,0.000000,0.436713,0.500642,1,1
148105,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,0.0,351464.0,328864.0,22600.0,1085100.0,0.047464,0.552223,0.642302,1,1
148106,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,52982.0,7500.0,0.0,7500.0,1650209.0,2.513060,0.992052,0.897052,1,1

In [7]:
# data['country_bank_1']=[x[:2] for x in data['BvDID_bank_1']]
# data = data.query('country_bank_1=="DE"')

# data['country_bank_2']=[x[:2] for x in data['BvDID_bank_2']]
# data = data.query('country_bank_2=="DE"')

# data['country_bank_3']=[x[:2] for x in data['BvDID_bank_3']]
# data = data.query('country_bank_3=="DE"')

data['postcode_bank_1'] = data['postcode_bank_1'].fillna(0)
data['postcode_bank_2'] = data['postcode_bank_2'].fillna(0)
data['postcode_bank_3'] = data['postcode_bank_3'].fillna(0)


data['postcode_bank_1'] = data['postcode_bank_1'].astype(str)
data['postcode_bank_2'] = data['postcode_bank_2'].astype(int)
data['postcode_bank_3'] = data['postcode_bank_3'].astype(int)

data['postcode_bank_2'] = data['postcode_bank_2'].astype(str)
data['postcode_bank_3'] = data['postcode_bank_3'].astype(str)

data['postcode_bank_1']=np.where(data['postcode_bank_1'].str.len()<5, "0"+data['postcode_bank_1'], data['postcode_bank_1'])
data['postcode_bank_2']=np.where(data['postcode_bank_2'].str.len()<5, "0"+data['postcode_bank_2'], data['postcode_bank_2'])
data['postcode_bank_3']=np.where(data['postcode_bank_3'].str.len()<5, "0"+data['postcode_bank_3'], data['postcode_bank_3'])



data=data.reset_index().drop(['index'], axis=1)
data.index=data.index+1

In [8]:
query_data = data.query('bank_type_1=="Savings banks"')
data.loc[:,'bank_ty_1'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

query_data = data.query('bank_type_2=="Savings banks"')
data.loc[:,'bank_ty_2'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

query_data = data.query('bank_type_3=="Savings banks"')
data.loc[:,'bank_ty_3'] = data.index.map(lambda x : 1 if x in query_data.index else 0)

In [9]:
data['post_affected_1_1']=[x[:1] for x in data['postcode_bank_1']]
data['post_affected_1_2']=[x[:1] for x in data['postcode_bank_2']]
data['post_affected_1_3']=[x[:1] for x in data['postcode_bank_3']]

data['post_affected_2_1']=[x[:2] for x in data['postcode_bank_1']]
data['post_affected_2_2']=[x[:2] for x in data['postcode_bank_2']]
data['post_affected_2_3']=[x[:2] for x in data['postcode_bank_3']]

# affected states: Sachsen, Nordrhein-Westfalen, Baden-WÃ¼rttemberg, Bayern, Hamburg, Schleswig-Holstein
# postcode of affected banks 
# 01 02 04 08 09
# 32 33 40 41 42 44 45 46 47 48151 48249 48282 48431 48599 48703 48653 49477 49525 50 51 52 53879 53937 53604 53111 57072 57462 57413 57439 57319 57392 57258 57271 58 59 
# 68 69 70 71 72 73 74 75 76646 76133 76530 76437 76275 77 78 79 88 89 97
# 63739 63897 8(80 81 82 83 84 85 86 87 88 89) 90 91 92 93 94 95 96 97 
# 20 21073 22 23701 23909 23552 24 25
# 34x 37x 43x


# bank_1
query_df_11 = data.query('postcode_bank_1=="48151"|postcode_bank_1=="48249"|postcode_bank_1=="48282"|postcode_bank_1=="48431"|postcode_bank_1=="48599"|postcode_bank_1=="48703"|postcode_bank_1=="48653"|postcode_bank_1=="49477"|postcode_bank_1=="49525"|postcode_bank_1=="53879"|postcode_bank_1=="53937"|postcode_bank_1=="53604"|postcode_bank_1=="53111"|postcode_bank_1=="57072"|postcode_bank_1=="57462"|postcode_bank_1=="57413"|postcode_bank_1=="57439"|postcode_bank_1=="57319"|postcode_bank_1=="57392"|postcode_bank_1=="57258"|postcode_bank_1=="57271"')          
data.loc[:,'bank_affected_11'] = data.index.map(lambda x : 1 if x in query_df_11.index else 0)

query_df_21 = data.query('post_affected_2_1=="01"|post_affected_2_1=="02"|post_affected_2_1=="04"|post_affected_2_1=="08"|post_affected_2_1=="09"|post_affected_2_1=="32"|post_affected_2_1=="33"|post_affected_2_1=="40"|post_affected_2_1=="41"|post_affected_2_1=="42"|post_affected_2_1=="44"|post_affected_2_1=="45"|post_affected_2_1=="46"|post_affected_2_1=="47"|post_affected_2_1=="50"|post_affected_2_1=="51"|post_affected_2_1=="52"|post_affected_2_1=="58"|post_affected_2_1=="59"|post_affected_2_1=="68"|post_affected_2_1=="69"|post_affected_2_1=="70"|post_affected_2_1=="71"|post_affected_2_1=="72"|post_affected_2_1=="73"|post_affected_2_1=="74"|post_affected_2_1=="75"|post_affected_2_1=="77"|post_affected_2_1=="78"|post_affected_2_1=="79"')                
data.loc[:,'bank_affected_21'] = data.index.map(lambda x : 1 if x in query_df_21.index else 0)

query_df_31 = data.query('post_affected_1_1=="8"|post_affected_2_1=="90"|post_affected_2_1=="91"|post_affected_2_1=="92"|post_affected_2_1=="93"|post_affected_2_1=="94"|post_affected_2_1=="95"|post_affected_2_1=="96"|post_affected_2_1=="97"|post_affected_2_1=="20"|post_affected_2_1=="22"|post_affected_2_1=="24"|post_affected_2_1=="25"|postcode_bank_1=="76646"|postcode_bank_1=="76133"|postcode_bank_1=="76530"|postcode_bank_1=="76437"|postcode_bank_1=="76275"|postcode_bank_1=="63739"|postcode_bank_1=="63897"|postcode_bank_1=="21073"|postcode_bank_1=="23701"|postcode_bank_1=="23909"|postcode_bank_1=="23552"')
data.loc[:,'bank_affected_31'] = data.index.map(lambda x : 1 if x in query_df_31.index else 0)

# bank_2
query_df_12 = data.query('postcode_bank_2=="48151"|postcode_bank_2=="48249"|postcode_bank_2=="48282"|postcode_bank_2=="48431"|postcode_bank_2=="48599"|postcode_bank_2=="48703"|postcode_bank_2=="48653"|postcode_bank_2=="49477"|postcode_bank_2=="49525"|postcode_bank_2=="53879"|postcode_bank_2=="53937"|postcode_bank_2=="53604"|postcode_bank_2=="53111"|postcode_bank_2=="57072"|postcode_bank_2=="57462"|postcode_bank_2=="57413"|postcode_bank_2=="57439"|postcode_bank_2=="57319"|postcode_bank_2=="57392"|postcode_bank_2=="57258"|postcode_bank_2=="57271"')          
data.loc[:,'bank_affected_12'] = data.index.map(lambda x : 1 if x in query_df_12.index else 0)

query_df_22 = data.query('post_affected_2_2=="01"|post_affected_2_2=="02"|post_affected_2_2=="04"|post_affected_2_2=="08"|post_affected_2_2=="09"|post_affected_2_2=="32"|post_affected_2_2=="33"|post_affected_2_2=="40"|post_affected_2_2=="41"|post_affected_2_2=="42"|post_affected_2_2=="44"|post_affected_2_2=="45"|post_affected_2_2=="46"|post_affected_2_2=="47"|post_affected_2_2=="50"|post_affected_2_2=="51"|post_affected_2_2=="52"|post_affected_2_2=="58"|post_affected_2_2=="59"|post_affected_2_2=="68"|post_affected_2_2=="69"|post_affected_2_2=="70"|post_affected_2_2=="71"|post_affected_2_2=="72"|post_affected_2_2=="73"|post_affected_2_2=="74"|post_affected_2_2=="75"|post_affected_2_2=="77"|post_affected_2_2=="78"|post_affected_2_2=="79"')                
data.loc[:,'bank_affected_22'] = data.index.map(lambda x : 1 if x in query_df_22.index else 0)

query_df_32 = data.query('post_affected_1_2=="8"|post_affected_2_2=="90"|post_affected_2_2=="91"|post_affected_2_2=="92"|post_affected_2_2=="93"|post_affected_2_2=="94"|post_affected_2_2=="95"|post_affected_2_2=="96"|post_affected_2_2=="97"|post_affected_2_2=="20"|post_affected_2_2=="22"|post_affected_2_2=="24"|post_affected_2_2=="25"|postcode_bank_2=="76646"|postcode_bank_2=="76133"|postcode_bank_2=="76530"|postcode_bank_2=="76437"|postcode_bank_2=="76275"|postcode_bank_2=="63739"|postcode_bank_2=="63897"|postcode_bank_2=="21073"|postcode_bank_2=="23701"|postcode_bank_2=="23909"|postcode_bank_2=="23552"')
data.loc[:,'bank_affected_32'] = data.index.map(lambda x : 1 if x in query_df_32.index else 0)

# bank_3
query_df_13 = data.query('postcode_bank_3=="48151"|postcode_bank_3=="48249"|postcode_bank_3=="48282"|postcode_bank_3=="48431"|postcode_bank_3=="48599"|postcode_bank_3=="48703"|postcode_bank_3=="48653"|postcode_bank_3=="49477"|postcode_bank_3=="49525"|postcode_bank_3=="53879"|postcode_bank_3=="53937"|postcode_bank_3=="53604"|postcode_bank_3=="53111"|postcode_bank_3=="57072"|postcode_bank_3=="57462"|postcode_bank_3=="57413"|postcode_bank_3=="57439"|postcode_bank_3=="57319"|postcode_bank_3=="57392"|postcode_bank_3=="57258"|postcode_bank_3=="57271"')          
data.loc[:,'bank_affected_13'] = data.index.map(lambda x : 1 if x in query_df_13.index else 0)

query_df_23 = data.query('post_affected_2_3=="01"|post_affected_2_3=="02"|post_affected_2_3=="04"|post_affected_2_3=="08"|post_affected_2_3=="09"|post_affected_2_3=="32"|post_affected_2_3=="33"|post_affected_2_3=="40"|post_affected_2_3=="41"|post_affected_2_3=="42"|post_affected_2_3=="44"|post_affected_2_3=="45"|post_affected_2_3=="46"|post_affected_2_3=="47"|post_affected_2_3=="50"|post_affected_2_3=="51"|post_affected_2_3=="52"|post_affected_2_3=="58"|post_affected_2_3=="59"|post_affected_2_3=="68"|post_affected_2_3=="69"|post_affected_2_3=="70"|post_affected_2_3=="71"|post_affected_2_3=="72"|post_affected_2_3=="73"|post_affected_2_3=="74"|post_affected_2_3=="75"|post_affected_2_3=="77"|post_affected_2_3=="78"|post_affected_2_3=="79"')                
data.loc[:,'bank_affected_23'] = data.index.map(lambda x : 1 if x in query_df_23.index else 0)

query_df_33 = data.query('post_affected_1_3=="8"|post_affected_2_3=="90"|post_affected_2_3=="91"|post_affected_2_3=="92"|post_affected_2_3=="93"|post_affected_2_3=="94"|post_affected_2_3=="95"|post_affected_2_3=="96"|post_affected_2_3=="97"|post_affected_2_3=="20"|post_affected_2_3=="22"|post_affected_2_3=="24"|post_affected_2_3=="25"|postcode_bank_3=="76646"|postcode_bank_3=="76133"|postcode_bank_3=="76530"|postcode_bank_3=="76437"|postcode_bank_3=="76275"|postcode_bank_3=="63739"|postcode_bank_3=="63897"|postcode_bank_3=="21073"|postcode_bank_3=="23701"|postcode_bank_3=="23909"|postcode_bank_3=="23552"')
data.loc[:,'bank_affected_33'] = data.index.map(lambda x : 1 if x in query_df_33.index else 0)


# 

query_df_1 = data.query('bank_affected_11==1|bank_affected_21==1|bank_affected_31==1')
data.loc[:,'bank_affected_1'] = data.index.map(lambda x : 1 if x in query_df_1.index else 0)

query_df_2 = data.query('bank_affected_12==1|bank_affected_22==1|bank_affected_32==1')
data.loc[:,'bank_affected_2'] = data.index.map(lambda x : 1 if x in query_df_2.index else 0)

query_df_3 = data.query('bank_affected_13==1|bank_affected_23==1|bank_affected_33==1')
data.loc[:,'bank_affected_3'] = data.index.map(lambda x : 1 if x in query_df_3.index else 0)

data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,bank_affected_31,bank_affected_12,bank_affected_22,bank_affected_32,bank_affected_13,bank_affected_23,bank_affected_33,bank_affected_1,bank_affected_2,bank_affected_3
1,DE2010019552,90530,9053,9576,Roth,Bayern,2010.0,DE13190,60311,623634.0,...,0,0,0,0,0,0,1,0,0,1
2,DE2010019552,90530,9053,9576,Roth,Bayern,2011.0,DE13190,60311,527219.0,...,0,0,0,0,0,0,1,0,0,1
3,DE2010019552,90530,9053,9576,Roth,Bayern,2012.0,DE13190,60311,525789.0,...,0,0,0,0,0,0,1,0,0,1
4,DE2010019739,15827,1582,12072,Teltow-FlÃ¤ming,Brandenburg,2012.0,DE13124,10787,9839.0,...,0,0,0,0,0,0,0,0,0,0
5,DE2010035090,12305,1230,11000,"Berlin, Stadt",Berlin,2010.0,DE13885,30159,12353.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,85399,8539,9178,Freising,Bayern,2012.0,DE13338,85435,1835.0,...,1,0,0,0,0,0,0,1,0,0
148103,DE8350273540,94362,9436,9278,Straubing-Bogen,Bayern,2012.0,DE13732,84028,3268.0,...,1,0,0,0,0,0,0,1,0,0
148104,DE8350275036,84307,8430,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,0,0,0,0,1,0,0
148105,DE8350276165,84339,8433,9277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,1,0,0,1,1,1,1
148106,DE8350277440,70469,7046,8111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,1,0,0,0,0,0,0,1,0,0

In [10]:
data['kreisschluessel'] = data['kreisschluessel'].astype(str)
data['kreisschluessel'] = np.where(data['kreisschluessel'].str.len()<5,"0"+data['kreisschluessel'],data['kreisschluessel'])

data

,BvDID_firm,plz_firm,matching,kreisschluessel,kreis,bundesland,year,BvDID_bank_1,postcode_bank_1,data2025_1,...,bank_affected_31,bank_affected_12,bank_affected_22,bank_affected_32,bank_affected_13,bank_affected_23,bank_affected_33,bank_affected_1,bank_affected_2,bank_affected_3
1,DE2010019552,90530,9053,09576,Roth,Bayern,2010.0,DE13190,60311,623634.0,...,0,0,0,0,0,0,1,0,0,1
2,DE2010019552,90530,9053,09576,Roth,Bayern,2011.0,DE13190,60311,527219.0,...,0,0,0,0,0,0,1,0,0,1
3,DE2010019552,90530,9053,09576,Roth,Bayern,2012.0,DE13190,60311,525789.0,...,0,0,0,0,0,0,1,0,0,1
4,DE2010019739,15827,1582,12072,Teltow-FlÃ¤ming,Brandenburg,2012.0,DE13124,10787,9839.0,...,0,0,0,0,0,0,0,0,0,0
5,DE2010035090,12305,1230,11000,"Berlin, Stadt",Berlin,2010.0,DE13885,30159,12353.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,85399,8539,09178,Freising,Bayern,2012.0,DE13338,85435,1835.0,...,1,0,0,0,0,0,0,1,0,0
148103,DE8350273540,94362,9436,09278,Straubing-Bogen,Bayern,2012.0,DE13732,84028,3268.0,...,1,0,0,0,0,0,0,1,0,0
148104,DE8350275036,84307,8430,09277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,0,0,0,0,1,0,0
148105,DE8350276165,84339,8433,09277,Rottal-Inn,Bayern,2012.0,DE13772,84307,1679.0,...,1,0,0,1,0,0,1,1,1,1
148106,DE8350277440,70469,7046,08111,Stuttgart,Baden-WÃ¼rttemberg,2012.0,DE13352,83022,4175.0,...,1,0,0,0,0,0,0,1,0,0

In [11]:
data.columns

Index(['BvDID_firm', 'plz_firm', 'matching', 'kreisschluessel', 'kreis',
       'bundesland', 'year', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       ...
       'bank_affected_31', 'bank_affected_12', 'bank_affected_22',
       'bank_affected_32', 'bank_affected_13', 'bank_affected_23',
       'bank_affected_33', 'bank_affected_1', 'bank_affected_2',
       'bank_affected_3'],
      dtype='object', length=110)

In [12]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'kreis', 'kreisschluessel', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected_1','bank_affected_2','bank_affected_3']]
data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected_1,bank_affected_2,bank_affected_3
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,0.824339,0.627641,1,1,0,0,1,0,0,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,0.063830,0.627641,1,1,0,0,1,0,0,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,0.538877,0.627641,1,1,0,0,1,0,0,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,0.630216,0.540324,1,1,0,1,0,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0.853153,0.741225,1,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.982878,0.733000,1,1,1,0,0,1,0,0
148103,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.832832,0.598721,1,1,1,0,0,1,0,0
148104,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.436713,0.500642,1,1,1,0,0,1,0,0
148105,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.552223,0.642302,1,1,1,0,0,1,1,1
148106,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,0.992052,0.897052,1,1,1,0,0,1,0,0

In [13]:
data.eval('tyaf_1 = bank_ty_1 * bank_affected_1', inplace=True)
data.eval('tyaf_2 = bank_ty_2 * bank_affected_2', inplace=True)
data.eval('tyaf_3 = bank_ty_3 * bank_affected_3', inplace=True)

data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected_1,bank_affected_2,bank_affected_3,tyaf_1,tyaf_2,tyaf_3
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1,0,0,1,0,0,1,0,0,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1,0,0,1,0,0,1,0,0,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1,0,0,1,0,0,1,0,0,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1,0,1,0,0,0,0,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,1,1,0,0,1,0,0,1,0,0
148103,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,1,1,0,0,1,0,0,1,0,0
148104,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,1,1,0,0,1,0,0,1,0,0
148105,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,1,1,0,0,1,1,1,1,0,0
148106,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,1,1,0,0,1,0,0,1,0,0

In [14]:
query_bank_affected = data.query('tyaf_1==1|tyaf_2==1|tyaf_3==1')
data.loc[:,'bank_affected'] = data.index.map(lambda x : 1 if x in query_bank_affected.index else 0)

data.eval('bank_affected_degree = tyaf_1 + tyaf_2 + tyaf_3', inplace=True)

/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [15]:
data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,bank_ty_2,bank_ty_3,bank_affected_1,bank_affected_2,bank_affected_3,tyaf_1,tyaf_2,tyaf_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,0,1,0,0,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,0,1,0,0,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,0,1,0,0,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1,0,0,0,0,0,0,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0,0,1,0,0,1,0,0,1,1
148103,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0,0,1,0,0,1,0,0,1,1
148104,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0,0,1,0,0,1,0,0,1,1
148105,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0,0,1,1,1,1,0,0,1,1
148106,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,0,0,1,0,0,1,0,0,1,1

In [16]:
data['bank_affected'].value_counts()

1    97926
0    50180
Name: bank_affected, dtype: int64

In [17]:
data['bank_affected_degree'].value_counts()

1    94011
0    50180
2     3794
3      121
Name: bank_affected_degree, dtype: int64

In [18]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'kreis', 'kreisschluessel', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected', 'bank_affected_degree']]
data

,BvDID_firm,year,plz_firm,kreis,kreisschluessel,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1.206676,0.824339,0.627641,1,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1.542198,0.063830,0.627641,1,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1.738739,0.538877,0.627641,1,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1.691839,0.630216,0.540324,1,1,0,1,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0.023150,0.853153,0.741225,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.183207,0.982878,0.733000,1,1,1,0,0,1,1
148103,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.006883,0.832832,0.598721,1,1,1,0,0,1,1
148104,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.000000,0.436713,0.500642,1,1,1,0,0,1,1
148105,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.047464,0.552223,0.642302,1,1,1,0,0,1,1
148106,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,2.513060,0.992052,0.897052,1,1,1,0,0,1,1

In [19]:
#data.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211219 - data.csv')

In [20]:
data['ort_1'] = data['kreis'].str.replace("Bad Doberan", "Rostock, Landkreis", n=-1)
data['ort_2'] = data['ort_1'].str.replace("GÃ¼strow", "Rostock, Landkreis", n=-1)

data['ort_3'] = data['ort_2'].str.replace("Demmin", "Mecklenburgische Seenplatte", n=-1)
data['ort_4'] = data['ort_3'].str.replace("Neubrandenburg", "Mecklenburgische Seenplatte", n=-1)
data['ort_5'] = data['ort_4'].str.replace("MÃ¼ritz", "Mecklenburgische Seenplatte", n=-1)
data['ort_6'] = data['ort_5'].str.replace("Mecklenburg-Strelitz", "Mecklenburgische Seenplatte", n=-1)

data['ort_7'] = data['ort_6'].str.replace("Uecker-Randow", "Vorpommern-Greifswald", n=-1)
data['ort_8'] = data['ort_7'].str.replace("Ostvorpommern", "Vorpommern-Greifswald", n=-1)
data['ort_9'] = data['ort_8'].str.replace("Greifswald", "Vorpommern-Greifswald", n=-1)

data['ort_10'] = data['ort_9'].str.replace("Stralsund", "Vorpommern-RÃ¼gen", n=-1)
data['ort_11'] = data['ort_10'].str.replace("Nordvorpommern", "Vorpommern-RÃ¼gen", n=-1)
data['ort_12'] = data['ort_11'].str.replace("RÃ¼gen", "Vorpommern-RÃ¼gen", n=-1)

data['ort_13'] = data['ort_12'].str.replace("Wismar", "Nordwestmecklenburg", n=-1)

data['ort_14'] = data['ort_13'].str.replace("Parchim", "Ludwigslust-Parchim", n=-1)
data['ort_15'] = data['ort_14'].str.replace("Ludwigslust", "Ludwigslust-Parchim", n=-1)





data['ort_16'] = data['ort_15'].str.replace("Kamenz", "Bautzen", n=-1)
data['ort_17'] = data['ort_16'].str.replace("Hoyerswerda, Stadt", "Bautzen", n=-1)

data['ort_18'] = data['ort_17'].str.replace("Riesa-GroÃenhain", "MeiÃen", n=-1)

data['ort_19'] = data['ort_18'].str.replace("WeiÃeritzkreis", "SÃ¤chsische Schweiz-Osterzgebirge", n=-1)
data['ort_20'] = data['ort_19'].str.replace("SÃ¤chsische Schweiz", "SÃ¤chsische Schweiz-Osterzgebirge", n=-1)

data['ort_21'] = data['ort_20'].str.replace("DÃ¶beln", "Mittelsachsen", n=-1)
data['ort_22'] = data['ort_21'].str.replace("Mittweida", "Mittelsachsen", n=-1)
data['ort_23'] = data['ort_22'].str.replace("Freiberg", "Mittelsachsen", n=-1)

data['ort_24'] = data['ort_23'].str.replace("Delitzsch", "Nordsachsen", n=-1)
data['ort_25'] = data['ort_24'].str.replace("Torgau-Oschatz", "Nordsachsen", n=-1)

data['ort_26'] = data['ort_25'].str.replace("Leipziger Land", "Leipzig, Landkreis", n=-1)
data['ort_27'] = data['ort_26'].str.replace("Muldentalkreis", "Leipzig, Landkreis", n=-1)

data['ort_28'] = data['ort_27'].str.replace("Chemnitzer Land", "Zwickau", n=-1)
data['ort_29'] = data['ort_28'].str.replace("Zwickauer Land", "Zwickau", n=-1)
data['ort_30'] = data['ort_29'].str.replace("Zwickau, Stadt", "Zwickau", n=-1)

data['ort_31'] = data['ort_30'].str.replace("Mittlerer Erzgebirgskreis", "Erzgebirgskreis", n=-1)
data['ort_32'] = data['ort_31'].str.replace("Annaberg", "Erzgebirgskreis", n=-1)
data['ort_33'] = data['ort_32'].str.replace("Stollberg", "Erzgebirgskreis", n=-1)
data['ort_34'] = data['ort_33'].str.replace("Aue-Schwarzenberg", "Erzgebirgskreis", n=-1)

data['ort_35'] = data['ort_34'].str.replace("LÃ¶bau-Zittau", "GÃ¶rlitz", n=-1)
data['ort_36'] = data['ort_35'].str.replace("GÃ¶rlitz, Stadt", "GÃ¶rlitz", n=-1)
data['ort_37'] = data['ort_36'].str.replace("Niederschlesischer Oberlausitzkreis", "GÃ¶rlitz", n=-1)

data['ort_38'] = data['ort_37'].str.replace("Plauen, Stadt", "Vogtlandkreis", n=-1)



data['ort_39'] = data['ort_38'].str.replace("Bitterfeld", "Anhalt-Bitterfeld", n=-1)
data['ort_40'] = data['ort_39'].str.replace("KÃ¶then", "Anhalt-Bitterfeld", n=-1)

data['ort_41'] = data['ort_40'].str.replace("Dessau, Stadt", "Dessau-RoÃlau", n=-1)

data['ort_42'] = data['ort_41'].str.replace("BÃ¶rdekreis", "BÃ¶rde", n=-1)
data['ort_43'] = data['ort_42'].str.replace("Ohrekreis", "BÃ¶rde", n=-1)

data['ort_44'] = data['ort_43'].str.replace("Bernburg", "Salzlandkreis", n=-1)
data['ort_45'] = data['ort_44'].str.replace("SchÃ¶nebeck", "Salzlandkreis", n=-1)
data['ort_46'] = data['ort_45'].str.replace("Aschersleben-StaÃfurt", "Salzlandkreis", n=-1)

data['ort_47'] = data['ort_46'].str.replace("WeiÃenfels", "Burgenlandkreis", n=-1)

data['ort_48'] = data['ort_47'].str.replace("Merseburg-Querfurt", "Saalekreis", n=-1)
data['ort_49'] = data['ort_48'].str.replace("Saalkreis", "Saalekreis", n=-1)

data['ort_50'] = data['ort_49'].str.replace("Halberstadt", "Harz", n=-1)
data['ort_51'] = data['ort_50'].str.replace("Quedlinburg", "Harz", n=-1)
data['ort_52'] = data['ort_51'].str.replace("Wernigerode", "Harz", n=-1)

data['ort_53'] = data['ort_52'].str.replace("Anhalt-Zerbst", "Wittenberg", n=-1)

data['ort_54'] = data['ort_53'].str.replace("Halle (Saale), Stadt", "Halle (Saale)", n=-1)

data['ort_55'] = data['ort_54'].str.replace("Mansfelder Land", "Mansfeld-SÃ¼dharz", n=-1)
data['ort'] = data['ort_55'].str.replace("Sangerhausen", "Mansfeld-SÃ¼dharz", n=-1)

/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:142: FutureWarning: The default value of regex will change from True to False in a future version.

In [21]:
data['regionalkey_1'] = data['kreisschluessel'].str.replace("Bad Doberan", "Rostock, Landkreis", n=-1)
data['ort_2'] = data['ort_1'].str.replace("GÃ¼strow", "Rostock, Landkreis", n=-1)

data['ort_3'] = data['ort_2'].str.replace("Demmin", "Mecklenburgische Seenplatte", n=-1)
data['ort_4'] = data['ort_3'].str.replace("Neubrandenburg", "Mecklenburgische Seenplatte", n=-1)
data['ort_5'] = data['ort_4'].str.replace("MÃ¼ritz", "Mecklenburgische Seenplatte", n=-1)
data['ort_6'] = data['ort_5'].str.replace("Mecklenburg-Strelitz", "Mecklenburgische Seenplatte", n=-1)

data['ort_7'] = data['ort_6'].str.replace("Uecker-Randow", "Vorpommern-Greifswald", n=-1)
data['ort_8'] = data['ort_7'].str.replace("Ostvorpommern", "Vorpommern-Greifswald", n=-1)
data['ort_9'] = data['ort_8'].str.replace("Greifswald", "Vorpommern-Greifswald", n=-1)

data['ort_10'] = data['ort_9'].str.replace("Stralsund", "Vorpommern-RÃ¼gen", n=-1)
data['ort_11'] = data['ort_10'].str.replace("Nordvorpommern", "Vorpommern-RÃ¼gen", n=-1)
data['ort_12'] = data['ort_11'].str.replace("RÃ¼gen", "Vorpommern-RÃ¼gen", n=-1)

data['ort_13'] = data['ort_12'].str.replace("Wismar", "Nordwestmecklenburg", n=-1)

data['ort_14'] = data['ort_13'].str.replace("Parchim", "Ludwigslust-Parchim", n=-1)
data['ort_15'] = data['ort_14'].str.replace("Ludwigslust", "Ludwigslust-Parchim", n=-1)


# regional key
data['regionalkey_1'] = data['kreisschluessel'].str.replace("13051", "13072", n=-1)
data['regionalkey_2'] = data['regionalkey_1'].str.replace("13053", "13072", n=-1)

data['regionalkey_3'] = data['regionalkey_2'].str.replace("13052", "13071", n=-1)
data['regionalkey_4'] = data['regionalkey_3'].str.replace("13002", "13071", n=-1)
data['regionalkey_5'] = data['regionalkey_4'].str.replace("13056", "13071", n=-1)
data['regionalkey_6'] = data['regionalkey_5'].str.replace("13055", "13071", n=-1)

data['regionalkey_7'] = data['regionalkey_6'].str.replace("13062", "13075", n=-1)
data['regionalkey_8'] = data['regionalkey_7'].str.replace("13059", "13075", n=-1)
data['regionalkey_9'] = data['regionalkey_8'].str.replace("13001", "13075", n=-1)

data['regionalkey_10'] = data['regionalkey_9'].str.replace("13005", "13073", n=-1)
data['regionalkey_11'] = data['regionalkey_10'].str.replace("13057", "13073", n=-1)
data['regionalkey_12'] = data['regionalkey_11'].str.replace("13061", "13073", n=-1)

data['regionalkey_13'] = data['regionalkey_12'].str.replace("13006", "13074", n=-1)
data['regionalkey_14'] = data['regionalkey_13'].str.replace("13058", "13074", n=-1)

data['regionalkey_15'] = data['regionalkey_14'].str.replace("13060", "13076", n=-1)
data['regionalkey_16'] = data['regionalkey_15'].str.replace("13054", "13076", n=-1)





data['regionalkey_17'] = data['regionalkey_16'].str.replace("14292", "14625", n=-1)
data['regionalkey_18'] = data['regionalkey_17'].str.replace("14262", "14625", n=-1)
data['regionalkey_19'] = data['regionalkey_18'].str.replace("14272", "14625", n=-1)

data['regionalkey_20'] = data['regionalkey_19'].str.replace("14285", "14627", n=-1)
data['regionalkey_21'] = data['regionalkey_20'].str.replace("14280", "14627", n=-1)

data['regionalkey_22'] = data['regionalkey_21'].str.replace("14290", "14628", n=-1)
data['regionalkey_23'] = data['regionalkey_22'].str.replace("14287", "14628", n=-1)

data['regionalkey_24'] = data['regionalkey_23'].str.replace("14375", "14522", n=-1)
data['regionalkey_25'] = data['regionalkey_24'].str.replace("14182", "14522", n=-1)
data['regionalkey_26'] = data['regionalkey_25'].str.replace("14177", "14522", n=-1)

data['regionalkey_27'] = data['regionalkey_26'].str.replace("14374", "14730", n=-1)
data['regionalkey_28'] = data['regionalkey_27'].str.replace("14389", "14730", n=-1)

data['regionalkey_29'] = data['regionalkey_28'].str.replace("14379", "14729", n=-1)
data['regionalkey_30'] = data['regionalkey_29'].str.replace("14383", "14729", n=-1)

data['regionalkey_31'] = data['regionalkey_30'].str.replace("14173", "14524", n=-1)
data['regionalkey_32'] = data['regionalkey_31'].str.replace("14193", "14524", n=-1)
data['regionalkey_33'] = data['regionalkey_32'].str.replace("14167", "14524", n=-1)

data['regionalkey_34'] = data['regionalkey_33'].str.replace("14181", "14521", n=-1)
data['regionalkey_35'] = data['regionalkey_34'].str.replace("14171", "14521", n=-1)
data['regionalkey_36'] = data['regionalkey_35'].str.replace("14188", "14521", n=-1)
data['regionalkey_37'] = data['regionalkey_36'].str.replace("14191", "14521", n=-1)

data['regionalkey_38'] = data['regionalkey_37'].str.replace("14286", "14626", n=-1)
data['regionalkey_39'] = data['regionalkey_38'].str.replace("14263", "14626", n=-1)
data['regionalkey_40'] = data['regionalkey_39'].str.replace("14284", "14626", n=-1)

data['regionalkey_41'] = data['regionalkey_40'].str.replace("14166", "14523", n=-1)
data['regionalkey_42'] = data['regionalkey_41'].str.replace("14178", "14523", n=-1)





data['regionalkey_43'] = data['regionalkey_42'].str.replace("15154", "15082", n=-1)
data['regionalkey_44'] = data['regionalkey_43'].str.replace("15159", "15082", n=-1)

data['regionalkey_45'] = data['regionalkey_44'].str.replace("15101", "15001", n=-1)

data['regionalkey_46'] = data['regionalkey_45'].str.replace("15355", "15083", n=-1)
data['regionalkey_47'] = data['regionalkey_46'].str.replace("15362", "15083", n=-1)

data['regionalkey_48'] = data['regionalkey_47'].str.replace("15153", "15089", n=-1)
data['regionalkey_49'] = data['regionalkey_48'].str.replace("15367", "15089", n=-1)
data['regionalkey_50'] = data['regionalkey_49'].str.replace("15352", "15089", n=-1)

data['regionalkey_51'] = data['regionalkey_50'].str.replace("15268", "15084", n=-1)
data['regionalkey_52'] = data['regionalkey_51'].str.replace("15256", "15084", n=-1)

data['regionalkey_53'] = data['regionalkey_52'].str.replace("15261", "15088", n=-1)
data['regionalkey_54'] = data['regionalkey_53'].str.replace("15265", "15088", n=-1)

data['regionalkey_55'] = data['regionalkey_54'].str.replace("15357", "15085", n=-1)
data['regionalkey_56'] = data['regionalkey_55'].str.replace("15364", "15085", n=-1)
data['regionalkey_57'] = data['regionalkey_56'].str.replace("15369", "15085", n=-1)

data['regionalkey_58'] = data['regionalkey_57'].str.replace("15151", "15091", n=-1)
data['regionalkey_59'] = data['regionalkey_58'].str.replace("15171", "15091", n=-1)

data['regionalkey_60'] = data['regionalkey_59'].str.replace("15202", "15002", n=-1)

data['regionalkey_61'] = data['regionalkey_60'].str.replace("15260", "15087", n=-1)
data['regionalkey_62'] = data['regionalkey_61'].str.replace("15266", "15087", n=-1)

data['regionalkey_63'] = data['regionalkey_62'].str.replace("15303", "15003", n=-1)
data['regionalkey_64'] = data['regionalkey_63'].str.replace("15358", "15086", n=-1)
data['regionalkey'] = data['regionalkey_64'].str.replace("15363", "15090", n=-1)

/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:116: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:149: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:150: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:152: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:154: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:155: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:157: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:158: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:159: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:161: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:162: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:164: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:165: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:167: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:168: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:169: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:171: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:172: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:176: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:177: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:179: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:180: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [22]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'ort', 'regionalkey', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected', 'bank_affected_degree']]
data

,BvDID_firm,year,plz_firm,ort,regionalkey,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1.206676,0.824339,0.627641,1,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1.542198,0.063830,0.627641,1,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1.738739,0.538877,0.627641,1,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1.691839,0.630216,0.540324,1,1,0,1,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11000,Berlin,DE13885,30159,12353.0,1332.0,...,0.023150,0.853153,0.741225,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.183207,0.982878,0.733000,1,1,1,0,0,1,1
148103,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.006883,0.832832,0.598721,1,1,1,0,0,1,1
148104,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.000000,0.436713,0.500642,1,1,1,0,0,1,1
148105,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.047464,0.552223,0.642302,1,1,1,0,0,1,1
148106,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,2.513060,0.992052,0.897052,1,1,1,0,0,1,1

In [23]:
data['ort_a'] = data['ort'].str.replace("Aachen, Stadt", "Aachen", n=-1)
data['ort_b'] = data['ort_a'].str.replace("Aachen", "StÃ¤dteregion Aachen", n=-1)

data['ort_c'] = data['ort_b'].str.replace("Hamburg, Freie und Hansestadt", "Hamburg", n=-1)

data['ort_d'] = data['ort_c'].str.replace("Soltau-Fallingbostel", "Heidekreis", n=-1)

data['ort_e'] = data['ort_d'].str.replace("Oldenburg", "Oldenburg, Landkreis", n=-1)

data['ort_f'] = data['ort_e'].str.replace("Daun", "Vulkaneifel", n=-1)

data['ort_'] = data['ort_f'].str.replace(", Hansestadt", "", n=-1)

data.loc[(data.regionalkey == "09571") ,'ort_'] = 'Ansbach, Landkreis'
data.loc[(data.regionalkey == "13076") ,'ort_'] = 'Ludwigslust-Parchim'
data.loc[(data.regionalkey == "13073") ,'ort_'] = 'Vorpommern-RÃ¼gen'
data.loc[(data.regionalkey == "13075") ,'ort_'] = 'Vorpommern-Greifswald'
data.loc[(data.regionalkey == "14628") ,'ort_'] = 'SÃ¤chsische Schweiz-Osterzgebirge'

data.loc[(data.ort_ == "Chemnitz, Stadt") ,'regionalkey'] = '14511'
data.loc[(data.ort_ == "Dresden, Stadt") ,'regionalkey'] = '14612'
data.loc[(data.ort_ == "Leipzig, Stadt") ,'regionalkey'] = '14713'
data.loc[(data.ort_ == "Altmarkkreis Salzwedel") ,'regionalkey'] = '15081'
data.loc[(data.ort_ == "GÃ¶ttingen") ,'regionalkey'] = '03159'
data.loc[(data.ort_ == "Bautzen") ,'regionalkey'] = '14625'

/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)
/Users/mxx/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [24]:
data['regionalkey_a'] = data['regionalkey'].str.replace("05313", "05334", n=-1)
data['regionalkey_b'] = data['regionalkey_a'].str.replace("05354", "05334", n=-1)

data['regionalkey_c'] = data['regionalkey_b'].str.replace("2000", "2", n=-1)

data['regionalkey_'] = data['regionalkey_c'].str.replace("11000", "11", n=-1)



# æ²¡æå¬å¸ï¼
# 06413 Offenbach
# 07313 Landau in der Pfalz
# 07338 Rhein-Pfalz-Kreis
# 08125 Heilbronn, Landkreis
# 08215 Karlsruhe, Landkreis
# 09162 MÃ¼nchen
# 09363 Weiden i.d. OPf.

In [25]:
# ort_df = data[['regionalkey_','ort_']]
# data['regionalkey_'].value_counts()
# data['ort_'].value_counts()

In [26]:
# ort_df = ort_df.drop_duplicates()
# ort_df=ort_df.reset_index().drop(['index'], axis=1)
# ort_df.index=ort_df.index+1
# ort_df

In [27]:
#ort_df.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211219_check county key.csv')

In [31]:
data=data[['BvDID_firm', 'year', 'plz_firm', 'ort_', 'regionalkey_', 'bundesland', 'BvDID_bank_1', 'postcode_bank_1', 'data2025_1',
       'data2075_1', 'data11750_1', 'data30680_1', 'data30690_1',
       'data38250_1', 'bank_type_1', 'liquidity_1', 'BvDID_bank_2',
       'postcode_bank_2', 'data2025_2', 'data2075_2', 'data11750_2',
       'data30680_2', 'data30690_2', 'data38250_2', 'bank_type_2',
       'liquidity_2', 'BvDID_bank_3', 'postcode_bank_3', 'data2025_3',
       'data2075_3', 'data11750_3', 'data30680_3', 'data30690_3',
       'data38250_3', 'bank_type_3', 'liquidity_3', 'fias', 'tfas', 'cash',
       'toas', 'shfd', 'ncli', 'ltdb', 'oncl', 'prov', 'culi', 'loan', 'cred',
       'wkca', 'ncas', 'empl', 'opre', 'turn', 'gros', 'staf', 'depr', 'cf',
       'rcem', 'rtas', 'dateinc_year_firm', 'sizecat', 'sector', 'adequacy',
       'hausbank', 'KID_firm', 'empllev', 'staflev', 'fiaslev', 'tfaslev',
       'cashlev', 'toaslev', 'provlev', 'ncaslev', 'turnlev', 'groslev',
       'deprlev', 'culilev', 'loanlev', 'credlev', 'nclilev', 'ltdblev',
       'oncllev', 'wkcalev', 'shfdlev', 'random', 'random_sample_indicator',
       'small', 'year_post', 'bank_ty_1', 'bank_ty_2', 'bank_ty_3',
       'bank_affected', 'bank_affected_degree']]
data

,BvDID_firm,year,plz_firm,ort_,regionalkey_,bundesland,BvDID_bank_1,postcode_bank_1,data2025_1,data2075_1,...,shfdlev,random,random_sample_indicator,small,year_post,bank_ty_1,bank_ty_2,bank_ty_3,bank_affected,bank_affected_degree
1,DE2010019552,2010.0,90530,Roth,09576,Bayern,DE13190,60311,623634.0,370294.0,...,1.206676,0.824339,0.627641,1,1,0,0,1,1,1
2,DE2010019552,2011.0,90530,Roth,09576,Bayern,DE13190,60311,527219.0,307754.0,...,1.542198,0.063830,0.627641,1,1,0,0,1,1,1
3,DE2010019552,2012.0,90530,Roth,09576,Bayern,DE13190,60311,525789.0,293639.0,...,1.738739,0.538877,0.627641,1,1,0,0,1,1,1
4,DE2010019739,2012.0,15827,Teltow-FlÃ¤ming,12072,Brandenburg,DE13124,10787,9839.0,644.0,...,1.691839,0.630216,0.540324,1,1,0,1,0,0,0
5,DE2010035090,2010.0,12305,"Berlin, Stadt",11,Berlin,DE13885,30159,12353.0,1332.0,...,0.023150,0.853153,0.741225,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148102,DE8350268089,2012.0,85399,Freising,09178,Bayern,DE13338,85435,1835.0,150.0,...,0.183207,0.982878,0.733000,1,1,1,0,0,1,1
148103,DE8350273540,2012.0,94362,Straubing-Bogen,09278,Bayern,DE13732,84028,3268.0,564.0,...,0.006883,0.832832,0.598721,1,1,1,0,0,1,1
148104,DE8350275036,2012.0,84307,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.000000,0.436713,0.500642,1,1,1,0,0,1,1
148105,DE8350276165,2012.0,84339,Rottal-Inn,09277,Bayern,DE13772,84307,1679.0,241.0,...,0.047464,0.552223,0.642302,1,1,1,0,0,1,1
148106,DE8350277440,2012.0,70469,Stuttgart,08111,Baden-WÃ¼rttemberg,DE13352,83022,4175.0,256.0,...,2.513060,0.992052,0.897052,1,1,1,0,0,1,1

In [32]:
data.to_csv(path_or_buf=r'/Users/mengxi/Desktop/financial research/final/211219_firmdata.csv')

# County level data

In [48]:
group = data.groupby('BvDID_firm')
affected_index = data.groupby('BvDID_firm').mean()['bank_affected']
df = affected_index.to_frame('affected_index')

query_df = df.query('affected_index!=0')
df.loc[:,'affected_firm'] = df.index.map(lambda x : 1 if x in query_df.index else 0)
df

              affected_index  affected_firm
BvDID_firm
DE2010019552             1.0              1
DE2010019739             0.0              0
DE2010035090             0.0              0
DE2010041272             1.0              1
DE2010061796             1.0              1
...                      ...            ...
DE8350268089             1.0              1
DE8350273540             1.0              1
DE8350275036             1.0              1
DE8350276165             1.0              1
DE8350277440             1.0              1

[58056 rows x 2 columns]

In [47]:
df['affected_firm'].value_counts()

1    38494
0    19562
Name: affected_firm, dtype: int64